// SF Commune Atlas — dataset v1.0.0
// Compiled 2026-07-31 from haight-st-commons.org, supernuclear.substack.com, ic.org,
// SF Standard, SFist, Wikipedia, FoundSF, The Bold Italic, house websites & press.
// Locations are intentionally neighborhood-approximate unless the address is public.
window.COMMUNE_DATA = {
  houses: [
    /* ---------- Haight Street Commons network ---------- */
    {
      id: 'agape', name: 'Agape', emoji: '🕊️',
      neighborhood: 'Mission Dolores', lat: 37.7601, lng: -122.4265, coordsApprox: true,
      residents: 16, founded: 2012, status: 'active', inHSC: 'yes',
      vibe: 'artists, engineers & earth-lovers',
      tags: ['art', 'music', 'events'],
      description: 'A 16-person intentional community in a historic Victorian near Dolores Park — artists, writers, DJs, musicians, entrepreneurs, engineers, and scientists unified by a vision of inspired communal living. Weekly Monday dinners, live music, film series, hot tub and firepit out back.',
      funFact: 'Rotating cooking and cleaning duties keep the Victorian humming; monthly check-ins keep the humans humming.',
      links: [
        { label: 'agapesf.org', url: 'https://www.agapesf.org/' },
        { label: 'instagram', url: 'https://www.instagram.com/agapeandfriends/' },
      ],
    },
    {
      id: 'embassy', name: 'The Embassy', emoji: '🏛️',
      neighborhood: 'Hayes Valley', lat: 37.7745, lng: -122.4290, coordsApprox: false,
      residents: 18, founded: 2012, status: 'active', inHSC: 'yes',
      vibe: 'governance lab & radical research',
      tags: ['tech', 'justice', 'governance'],
      description: 'A 1900 mansion on Webster St and flagship of the international Embassy Network (co-founded by former NASA scientists). Residents prototype alternative governance and justice systems, host formerly incarcerated community members, and run the house by doocracy.',
      funFact: 'The Embassy Network spans houses across North America, Latin America, and Europe — this is where it started.',
      links: [
        { label: 'embassynetwork.com', url: 'https://embassynetwork.com/' },
        { label: 'archive', url: 'https://www.haight.place/Embassy/' },
      ],
    },
    {
      id: 'rgb', name: 'RGB House', emoji: '🌈',
      neighborhood: 'Lower Haight', lat: 37.7717, lng: -122.4310, coordsApprox: true,
      residents: 11, founded: 2015, status: 'active', inHSC: 'yes',
      vibe: 'art shows, lectures & slackocracy',
      tags: ['art', 'events'],
      description: 'Eleven long-term residents in a 3,100 sq ft Victorian — 9 bedrooms, 4 bathrooms, 3 living rooms — governed through a playful mix of doocracy, adhocracy, and "Slackocracy." Hosts art shows and lecture series.',
      funFact: 'Monthly dues of ~$255 cover food, utilities, cleaning, and events for the whole house.',
      links: [
        { label: 'rgb-house.com', url: 'https://www.rgb-house.com/' },
        { label: 'supernuclear case study', url: 'https://supernuclear.substack.com/p/case-study-the-story-of-rgb-2c0974654cde' },
      ],
    },
    {
      id: 'redvic', name: 'The Red Victorian', emoji: '❤️',
      neighborhood: 'Upper Haight', lat: 37.7695, lng: -122.4487, coordsApprox: false,
      residents: 20, founded: 1977, closedYear: 2022, status: 'closed', inHSC: 'maybe',
      vibe: 'peace, love & queer art hotel',
      tags: ['queer', 'art', 'historical'],
      description: 'The legendary 1904 "peace and love" hotel at 1665 Haight — Sami Sunchild\'s B&B turned Embassy Network co-living house with 20 rooms, a counterculture landmark since the Summer of Love. In 2020–21 it housed the Fishbowl Collective of trans and QTPOC artists before the building sold in 2022.',
      funFact: 'Started life as the Jefferson Hotel in 1904; survived every era of the Haight since.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/The_Red_Victorian' },
        { label: 'history blog', url: 'https://redvichistory.wordpress.com/' },
      ],
    },
    {
      id: 'manzanita', name: 'Manzanita', emoji: '🌿',
      neighborhood: 'Outer Richmond', lat: 37.7667, lng: -122.4567, coordsApprox: true,
      residents: 12, founded: 2016, status: 'active', inHSC: 'yes',
      vibe: 'radical self-love & sustainability',
      tags: ['wellness'],
      description: 'A twelve-resident community built on radical self-love, kindness, curiosity, and environmental sustainability, with radical inclusion as a core value.',
      links: [],
    },
    {
      id: 'beacon', name: 'Beacon House', emoji: '🔆',
      neighborhood: 'Mission', lat: 37.7513, lng: -122.4103, coordsApprox: false,
      residents: 8, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'cooperation, honesty & playful agency',
      tags: ['wellness'],
      description: 'Eight residents (25–33) on Florida St living by values of cooperation, sharing, integrity, growth, and playful autonomy. Twice-weekly dinners and tri-weekly house meetings.',
      links: [],
    },
    {
      id: 'twentymish', name: '20mish', emoji: '🖥️',
      neighborhood: 'Mission', lat: 37.7589, lng: -122.4189, coordsApprox: false,
      residents: 40, founded: 2012, status: 'active', inHSC: 'maybe',
      vibe: 'hacker house turned creative village',
      tags: ['tech', 'hacker'],
      description: 'A 40-bedroom co-living building at 20th & Mission (Walk Score 99), founded in 2012 as the first crypto hacker house. Now home to AI engineers, designers, founders, scientists, chefs, and social workers, with a co-working office, media room, and courtyard.',
      funFact: '3 blocks from Dolores Park, 2 from Noisebridge, 4 from BART.',
      links: [
        { label: '20mish.com', url: 'https://20mish.com/' },
        { label: 'twitter', url: 'https://x.com/20mish_sf' },
      ],
    },
    {
      id: 'ubuntu', name: 'Chateau Ubuntu', emoji: '🏰',
      neighborhood: 'Alamo Square', lat: 37.7743, lng: -122.4330, coordsApprox: false,
      residents: 38, founded: 2015, closedYear: 2020, status: 'closed', inHSC: 'maybe',
      vibe: '"I am because you are"',
      tags: ['events', 'wellness'],
      description: 'A historic 10-bedroom 1894 mansion on Fell St that housed up to 38 people under the Ubuntu philosophy — shared meals, gratitude circles, radical acceptance, and yes, cuddle puddles. The Planning Department cited it for illegal occupancy in 2017 and the experiment eventually wound down.',
      funFact: 'Its governance experiments influenced the houses that came after it.',
      links: [
        { label: 'sfist coverage', url: 'https://sfist.com/2017/01/26/uhoh_chateau_ubuntu/' },
      ],
    },
    {
      id: 'chaortica', name: 'Chaortica', emoji: '🌀',
      neighborhood: 'Ashbury Heights', lat: 37.7688, lng: -122.4467, coordsApprox: true,
      residents: 8, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'silly, radical, flat as a pancake',
      tags: ['art'],
      description: 'A community of radical, ambitious, inquisitive humans in a century-old house with a garden and greenhouse near the Haight-Ashbury crossroads. Governance is consensus and do-ocracy with a hard commitment to flatness — no member has more authority than any other.',
      funFact: 'Their membership agreement lives in a public GitHub repo.',
      links: [
        { label: 'github', url: 'https://github.com/jtschoonhoven/chaortica' },
      ],
    },
    {
      id: 'template', name: 'Template House', emoji: '✊',
      neighborhood: 'Lower Haight', lat: 37.7729, lng: -122.4270, coordsApprox: true,
      residents: 5, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'second chances & solidarity',
      tags: ['justice'],
      description: 'Five residents exploring co-creation and solidarity in a substance- and weapon-free space. Home of the Second Life community for formerly incarcerated people, with a semi-public community living room that hosts "Revolution Sunday."',
      links: [
        { label: 'second life project', url: 'https://www.secondlifeproject.net/spaces' },
      ],
    },
    {
      id: 'readingroom', name: 'The Radical Reading Room', emoji: '📚',
      neighborhood: 'Lower Haight', lat: 37.7722, lng: -122.4297, coordsApprox: false,
      residents: null, founded: 2021, status: 'active', inHSC: 'yes',
      vibe: 'the quietest room in the commons',
      tags: ['events', 'community space'],
      description: 'Not a house but the network\'s public living room: a 700 sq ft free space on Haight St for quiet reading, writing, and study, run by volunteers at no charge. No talking, no calls, no meetings — but free jam sessions, reading groups, and watch parties after hours.',
      links: [
        { label: 'theradicalreadingroom.org', url: 'https://theradicalreadingroom.org/' },
      ],
    },
    {
      id: 'kaleidoscope', name: 'Kaleidoscope', emoji: '🎨',
      neighborhood: 'Mission', lat: 37.7570, lng: -122.4155, coordsApprox: true,
      residents: 9, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'art, dance & emotional connection',
      tags: ['art', 'music', 'events'],
      description: 'Nine people focused on art, music, and dance in a 7-room house in the heart of the Mission. Clothing swaps, art nights, dinner parties, dance parties — and a deliberate culture of community care, vulnerability, and emotional connection.',
      links: [
        { label: 'website', url: 'https://sites.google.com/view/kscomission' },
      ],
    },
    {
      id: 'crest', name: 'Crest', emoji: '⛰️',
      neighborhood: 'Lower Haight', lat: 37.7712, lng: -122.4325, coordsApprox: true,
      residents: 10, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'self-development & diversity',
      tags: ['wellness'],
      description: 'Nine to ten residents prioritizing self-development, diversity, and a mission-driven, cooperative orientation.',
      links: [],
    },
    {
      id: 'chrysalis', name: 'Chrysalis', emoji: '🦋',
      neighborhood: 'Berkeley', lat: 37.8716, lng: -122.2727, coordsApprox: true,
      residents: 15, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'a home for life transitions',
      tags: ['family', 'co-parenting'],
      description: 'A fifteen-person intergenerational community in Berkeley for people in major life transitions — career changes, parenthood, new ventures. Family-style living with regular shared meals among technologists, parents, artists, scientists, teachers, and comedians.',
      links: [
        { label: 'chrysalisberkeley.com', url: 'https://chrysalisberkeley.com/' },
      ],
    },
    {
      id: 'realhouse', name: 'The Real House', emoji: '🍄',
      neighborhood: 'Alamo Square', lat: 37.7757, lng: -122.4370, coordsApprox: true,
      residents: null, founded: 2019, status: 'active', inHSC: 'yes',
      vibe: 'psychedelic, vivacious, real',
      tags: ['wellness', 'events'],
      description: 'Founded May 2019 as a space to "get real" with loving community. A vivacious, psychedelic, intentional home two blocks from Alamo Square, with a garden of apple trees, plum trees, and blackberries. Hosts Hippie Happy Hours, Sad Parties, Yoga Nidra, and acro yoga.',
      funFact: 'Yes, "Sad Parties" is a recurring event, and reportedly a great one.',
      links: [],
    },
    {
      id: 'grammys', name: "Grammy's House", emoji: '🐔',
      neighborhood: 'Inner Richmond', lat: 37.7742, lng: -122.4673, coordsApprox: true,
      residents: 7, founded: 2011, status: 'active', inHSC: 'yes',
      vibe: 'crafting, cooking & cozying',
      tags: ['music', 'events'],
      description: 'Seven humans, two friendly felines, and three friendly hens crafting, cooking, and cozying since 2011. Monthly living-room concerts (Groupmuse regulars), potlucks, fundraisers, and skillshares.',
      funFact: 'The hens are considered members.',
      links: [
        { label: 'instagram', url: 'https://www.instagram.com/grammyshousecoop/' },
        { label: 'facebook', url: 'https://www.facebook.com/grammys.house.coop/' },
      ],
    },
    {
      id: 'nuhaus', name: 'NuHaus', emoji: '🔥',
      neighborhood: 'Alamo Square', lat: 37.7752, lng: -122.4340, coordsApprox: true,
      residents: 11, founded: 2016, status: 'active', inHSC: 'yes',
      vibe: 'intentionally unintentional',
      tags: ['burner', 'art'],
      description: 'Eleven people in a Victorian near Alamo Square, founded January 2016 by a crew leaving warehouse living. "Intentionally unintentional or unintentionally intentional, depending on who you ask" — kind, chill, crafty, Burner-y, allergic to mandatory structure.',
      links: [
        { label: 'facebook', url: 'https://www.facebook.com/onesixtwoone/' },
      ],
    },
    {
      id: 'village', name: 'The Village', emoji: '🧒',
      neighborhood: 'Panhandle', lat: 37.7655, lng: -122.4527, coordsApprox: true,
      residents: 19, founded: 2022, status: 'active', inHSC: 'maybe',
      vibe: 'raising kids together, not alone',
      tags: ['family', 'co-parenting'],
      description: 'A multigenerational co-living home of ~15 adults and 4 kids across three vertically-stacked units near the Panhandle. Non-hierarchical decision-making with equal say for every adult; a flagship Supernuclear case study in turning single-family housing into harmonious coliving.',
      links: [
        { label: 'villagehousesf.org', url: 'https://villagehousesf.org/the-residents' },
        { label: 'supernuclear case study', url: 'https://supernuclear.substack.com/p/case-study-the-village-san-francisco' },
      ],
    },
    {
      id: 'eucalyptus', name: 'Eucalyptus', emoji: '🌳',
      neighborhood: 'Panhandle', lat: 37.7725, lng: -122.4460, coordsApprox: false,
      residents: null, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'diverse professionals, many hobbies',
      tags: ['events'],
      description: 'A community of late-twenties to mid-thirties residents on Fell St by the Panhandle, with a deliberately wide mix of professions and hobbies.',
      links: [
        { label: 'facebook', url: 'https://www.facebook.com/eucalyptushaus/' },
      ],
    },
    {
      id: 'muse', name: 'The Muse', emoji: '🎭',
      neighborhood: 'NoPa', lat: 37.7773, lng: -122.4440, coordsApprox: false,
      residents: 13, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'low-key home, high-key parties',
      tags: ['art', 'events'],
      description: 'A 13-bedroom, 6.5-bath Victorian on Golden Gate Ave with residents mid-20s to mid-30s and minimal hard rules. Hobbies run from volleyball and fusion dance to 3D printing and immersive art; their Spring Bacchanalia made the SF Standard.',
      links: [
        { label: 'sf standard', url: 'https://sfstandard.com/2024/03/19/the-muse-sf-spring-bacchanalia-party/' },
      ],
    },
    {
      id: 'mcallister', name: 'McAllister House', emoji: '🏡',
      neighborhood: 'NoPa', lat: 37.7778, lng: -122.4390, coordsApprox: true,
      residents: 13, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'fun-loving weekly-dinner crew',
      tags: ['events'],
      description: 'Thirteen residents, mid-twenties to mid-thirties, with weekly dinners and occasional larger community events.',
      links: [],
    },
    {
      id: 'atrium', name: 'Atrium', emoji: '🪴',
      neighborhood: 'NoPa', lat: 37.7768, lng: -122.4405, coordsApprox: true,
      residents: null, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'warmth, connection & natural light',
      tags: ['wellness'],
      description: 'Community living self-described as "nicer, cleaner, and more spacious than your typical SF group house," valuing connection, warmth, and multi-generational community.',
      links: [],
    },
    {
      id: 'soa', name: 'Start of Anything', emoji: '🌱',
      neighborhood: 'Mission', lat: 37.7605, lng: -122.4180, coordsApprox: true,
      residents: 7, founded: 2022, status: 'active', inHSC: 'yes',
      vibe: 'science, AI & fifty potted plants',
      tags: ['tech'],
      description: 'Seven residents working across science, engineering, event planning, government, AI, and healthcare. The house keeps roughly 50 potted plants alive, which may be the most impressive collaboration of all.',
      links: [],
    },
    {
      id: 'thalia', name: 'Thalia', emoji: '✨',
      neighborhood: 'NoPa', lat: 37.7760, lng: -122.4415, coordsApprox: true,
      residents: null, founded: 2024, status: 'active', inHSC: 'yes',
      vibe: 'joy, generosity & abundance',
      tags: ['wellness'],
      description: 'One of the network\'s newest houses (October 2024), centered on warmth and "energetic home-making": belonging, virtuous cycles of generosity, clear and empathetic communication, and beautification.',
      links: [],
    },
    {
      id: 'treehouse', name: 'Treehouse', emoji: '🌲',
      neighborhood: 'Hayes Valley', lat: 37.7758, lng: -122.4245, coordsApprox: true,
      residents: 19, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'trauma-informed co-parenting',
      tags: ['family', 'co-parenting', 'justice'],
      description: 'Thirteen adults and six children across three interconnected units, focused on co-parenting — including fostering — and trauma-informed living: authentic, liberated, loving, resilient, sustainable.',
      links: [],
    },
    {
      id: 'heartloom', name: 'Heartloom', emoji: '🧵',
      neighborhood: 'North Berkeley', lat: 37.8850, lng: -122.2594, coordsApprox: true,
      residents: 15, founded: 2022, status: 'active', inHSC: 'yes',
      vibe: 'hearts interwoven on a loom',
      tags: ['queer', 'art'],
      description: 'Founded early 2022 in the North Berkeley hills. An LGBTQIA+-friendly space oriented toward creation and engagement with the world: the heart is care for each other, the loom is the interweaving of aspirations. Clothing swaps, art nights, dinner-dance parties.',
      links: [],
    },
    {
      id: 'sigil', name: 'Sigil House', emoji: '🔮',
      neighborhood: 'Lower Haight', lat: 37.7735, lng: -122.4287, coordsApprox: true,
      residents: 5, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'transformation & alternative justice',
      tags: ['justice'],
      description: 'A five-bedroom Lower Haight house where three returning citizens and two never-incarcerated housemates live as one autonomous community built around transformation, empowerment, and alternative justice — a sister house to Template.',
      links: [
        { label: 'second life project', url: 'https://www.secondlifeproject.net/spaces' },
      ],
    },
    {
      id: 'presidio', name: 'Presidio Mansion', emoji: '🐕',
      neighborhood: 'Presidio', lat: 37.7980, lng: -122.4650, coordsApprox: true,
      residents: 6, founded: null, status: 'active', inHSC: 'yes',
      vibe: 'four houses, one community',
      tags: ['events'],
      description: 'Six residents plus a dog in a large Victorian with a sun room, grand foyer, and a massive entertainment room — part of a four-house cluster of 25+ people.',
      links: [],
    },
    {
      id: 'centersf', name: 'The Center SF', emoji: '🍵',
      neighborhood: 'Lower Haight', lat: 37.7724, lng: -122.4304, coordsApprox: false,
      residents: 25, founded: null, closedYear: 2025, status: 'closed', inHSC: 'maybe',
      vibe: 'tea house, yoga & ecstatic dance',
      tags: ['wellness', 'events', 'spiritual'],
      description: 'A decade-old teahouse, events space, and 19-room co-living hub at 548 Fillmore for artists, Burners, bodyworkers, and techies — yoga, ecstatic dance, authentic relating. Closed June 2025 after city enforcement and leadership disputes; a resurrection as the nonprofit Gather SF is underway.',
      links: [
        { label: 'thecentersf.com', url: 'https://www.thecentersf.com/' },
        { label: 'gather sf story', url: 'https://sfstandard.com/2025/09/16/the-center-resurrects-as-gather-sf-teahouse-community-hub/' },
      ],
    },
    {
      id: 'convent', name: 'The Convent', emoji: '⛪',
      neighborhood: 'Lower Haight', lat: 37.7734, lng: -122.4300, coordsApprox: true,
      residents: 24, founded: null, status: 'active', inHSC: 'maybe',
      vibe: 'an art collective in a former rectory',
      tags: ['art', 'music', 'events'],
      description: 'A three-story former rectory at Fillmore & Oak housing 24 artists across creative disciplines — 19 bedrooms, a healing sanctuary, a chapel, a recording studio, and a tea house in the basement.',
      funFact: 'Yes, there is a real chapel, and yes, it hosts shows.',
      links: [
        { label: 'theconventarthouse.com', url: 'https://www.theconventarthouse.com/' },
      ],
    },
    {
      id: 'mushrooms', name: 'Thriving Mushrooms', emoji: '🍄‍🟫',
      neighborhood: 'Noe Valley', lat: 37.7436, lng: -122.4366, coordsApprox: true,
      residents: null, founded: null, status: 'unknown', inHSC: 'yes',
      vibe: 'mindfulness, play & planet justice',
      tags: ['wellness', 'spiritual'],
      description: 'An intentional community anchored in self-growth and mutual support, organizing life around four pillars: Mindfulness & Healing, Playfulness, Art & Creativity, and Social & Planet Justice.',
      links: [],
    },
    {
      id: 'rabbithole', name: 'The Rabbithole', emoji: '🐇',
      neighborhood: 'Glen Park', lat: 37.7386, lng: -122.4519, coordsApprox: true,
      residents: null, founded: null, status: 'unknown', inHSC: 'yes',
      vibe: 'kind, playful & delightfully odd',
      tags: ['art'],
      description: 'An experiment in a better way to live: residents share more of their lives, grow together, and cultivate a uniquely kind, playful, odd community space down in Glen Park.',
      links: [],
    },
    {
      id: 'archive', name: 'The Archive', emoji: '🗄️',
      neighborhood: 'Mission Dolores', lat: 37.7614, lng: -122.4250, coordsApprox: true,
      residents: null, founded: null, status: 'unknown', inHSC: 'yes',
      vibe: 'quietly legendary',
      tags: ['tech'],
      description: 'A long-running group house in the Mission Dolores area, listed in the Haight Street Commons directory. Details are scarce by design — some houses prefer the quiet life.',
      links: [],
    },
    {
      id: 'manor', name: 'The Manor of Being', emoji: '🧘',
      neighborhood: 'Mission', lat: 37.7560, lng: -122.4130, coordsApprox: true,
      residents: null, founded: null, status: 'unknown', inHSC: 'yes',
      vibe: 'being, in manor form',
      tags: ['spiritual'],
      description: 'An intentional community in the Mission listed in the Haight Street Commons directory; the name promises a lot and the house keeps the rest mysterious.',
      links: [],
    },

    /* ---------- the wider scene & the ancestors ---------- */
    {
      id: 'kerista', name: 'Kerista Commune', emoji: '💞',
      neighborhood: 'Cole Valley / Haight', lat: 37.7674, lng: -122.4498, coordsApprox: true,
      residents: 30, founded: 1971, closedYear: 1991, status: 'historical', inHSC: 'no',
      vibe: 'polyfidelity & Macintosh dealing',
      tags: ['historical', 'free love', 'tech'],
      description: 'The legendary 1971–1991 commune of Bro Jud and Eve Furchgott that coined the word "polyfidelity." Members practiced group marriage with nightly rotation schedules, shared all income — and funded it all by running Abacus, one of the biggest early Macintosh dealerships in the Bay.',
      funFact: 'A free-love commune that was also, improbably, a top Apple reseller of the 1980s.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kerista' },
        { label: 'kerista.com archive', url: 'https://www.kerista.com/' },
      ],
    },
    {
      id: 'diggers', name: 'The Diggers', emoji: '🍞',
      neighborhood: 'Haight-Ashbury', lat: 37.7699, lng: -122.4460, coordsApprox: true,
      residents: null, founded: 1966, closedYear: 1968, status: 'historical', inHSC: 'no',
      vibe: 'everything free, forever',
      tags: ['historical', 'justice', 'art'],
      description: 'Anarchist street-theater artists and mutual-aid pioneers of the Summer of Love: free food in the Panhandle every day at 4pm, Free Stores, free concerts, and happenings like the Death of Money Parade. The spiritual ancestors of every free fridge and mutual-aid network in the city.',
      funFact: 'To get free stew you had to step through a giant yellow picture frame — the "Free Frame of Reference."',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/San_Francisco_Diggers' },
        { label: 'atlas obscura', url: 'https://www.atlasobscura.com/articles/diggers-san-francisco' },
      ],
    },
    {
      id: 'kaliflower', name: 'Kaliflower Commune', emoji: '🌼',
      neighborhood: 'Western Addition', lat: 37.7857, lng: -122.4390, coordsApprox: true,
      residents: null, founded: 1967, closedYear: 1972, status: 'historical', inHSC: 'no',
      vibe: 'free love & gay liberation press',
      tags: ['historical', 'queer', 'free love'],
      description: 'The Sutter/Scott Street commune that published the Kaliflower newsletter (1969–71), hand-delivered weekly to 300+ communes — the social network of the SF commune scene. Bridged hippie free love with early gay liberation.',
      funFact: 'Thursdays were "Kaliflower Day," the intercommunal delivery ritual that stitched the whole scene together.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kaliflower_Commune' },
        { label: 'outhistory', url: 'https://outhistory.org/exhibits/show/kali/kaliintro' },
      ],
    },
    {
      id: 'projectone', name: 'Project One', emoji: '🏭',
      neighborhood: 'SoMa', lat: 37.7742, lng: -122.4137, coordsApprox: false,
      residents: 200, founded: 1970, closedYear: 1980, status: 'historical', inHSC: 'no',
      vibe: "SF's first warehouse community",
      tags: ['historical', 'art', 'tech'],
      description: 'An 84,000 sq ft abandoned candy factory at 1380 Howard turned into San Francisco\'s first warehouse community (1970–1980): students, craftspeople, sculptors, filmmakers, and technologists governed by weekly consensus meetings and nothing else.',
      funFact: 'Hosted Resource One, one of the first public-access computer centers — communal living meets proto-internet.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Project_One_(San_Francisco)' },
        { label: 'foundsf', url: 'https://www.foundsf.org/Project_One_Warehouse' },
      ],
    },
    {
      id: 'morningstar', name: 'Morningstar Ranch', emoji: '☀️',
      neighborhood: 'Occidental (Sonoma)', lat: 38.3736, lng: -122.6378, coordsApprox: true,
      residents: 150, founded: 1966, closedYear: 1971, status: 'historical', inHSC: 'no',
      vibe: 'open land, denied to no one',
      tags: ['historical', 'free love'],
      description: 'Lou Gottlieb\'s 31-acre open-land commune an hour north of the city, run on the principle "Land Access To Which Is Denied No One." Drew 150+ residents at its peak and served as the country retreat for the Haight scene — until Sonoma County bulldozed the structures.',
      funFact: 'Gottlieb (of the Limeliters) tried to deed the land to God; the county assessor declined.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Morningstar_Commune' },
      ],
    },
    {
      id: 'struggle', name: 'Struggle Mountain', emoji: '🏔️',
      neighborhood: 'Los Altos Hills', lat: 37.3667, lng: -122.1200, coordsApprox: true,
      residents: 15, founded: 1966, status: 'active', inHSC: 'no',
      vibe: "the last '60s commune standing",
      tags: ['historical', 'family', 'music'],
      description: 'The Bay Area\'s last continuously-running 1960s-style commune: 10 adults and 5 kids on 10 acres above Palo Alto, community-owned since 1976. Named by Joan Baez, who lived there in the \'70s; Allen Ginsberg was a house guest.',
      funFact: 'Nearly 60 years old and still going — the elder of every house on this map.',
      links: [
        { label: 'ic.org directory', url: 'https://www.ic.org/directory/struggle-mountain/' },
      ],
    },
    {
      id: 'radish', name: 'Radish', emoji: '🌶️',
      neighborhood: 'Oakland', lat: 37.8044, lng: -122.2708, coordsApprox: true,
      residents: 28, founded: 2020, status: 'active', inHSC: 'no',
      vibe: 'the friend-compound blueprint',
      tags: ['family', 'co-parenting'],
      description: 'An Oakland residential compound of 20 adults and 8 kids across mixed unit types, created by Supernuclear\'s Phil Levin and Kristen Berman. The model home of the "friend compound" movement — now splitting amoeba-style into three new East Bay compounds as the families grow.',
      links: [
        { label: 'radishoakland.com', url: 'https://radishoakland.com/' },
        { label: 'supernuclear', url: 'https://supernuclear.substack.com/p/radish-is-officially-for-sale' },
      ],
    },
    {
      id: 'bsc', name: 'Berkeley Student Cooperative', emoji: '🎓',
      neighborhood: 'Berkeley', lat: 37.8716, lng: -122.2596, coordsApprox: true,
      residents: 1300, founded: 1933, status: 'active', inHSC: 'no',
      vibe: 'the co-op mothership',
      tags: ['students', 'historical'],
      description: 'The largest student housing cooperative in the United States: 1,300+ members across 20 houses around the UC Berkeley campus, born in the Great Depression and still run democratically, with every member contributing work hours to keep rent low.',
      funFact: 'Founded in 1933 — it has outlived every commune on this map except nobody, because it never stopped.',
      links: [
        { label: 'bsc.coop', url: 'https://www.bsc.coop/' },
        { label: 'nasco', url: 'https://www.nasco.coop/' },
      ],
    },
  ],
};
