// SF Commune Atlas — dataset v1.3.0
// Compiled 2026-07-31 from haight-st-commons.org, supernuclear.substack.com, ic.org,
// SF Standard, SFist, Wikipedia, FoundSF, OutHistory, diggers.org, The Bold Italic,
// KQED, house websites & era press.
// Privacy: ACTIVE houses are anonymized to the block (coords rounded, no addresses).
// CLOSED & HISTORICAL houses show exact addresses where the historical record has them.
// foundedEst = our estimate for timeline placement when the house doesn't publish a date.
window.COMMUNE_DATA = {
  houses: [
    /* ================= Haight Street Commons network & the living scene ================= */
    {
      id: 'agape', name: 'Agape', emoji: '🕊️',
      neighborhood: 'Mission Dolores', lat: 37.760, lng: -122.427, coordsApprox: true,
      residents: 16, founded: 2012, status: 'active', inHSC: 'yes',
      vibe: 'artists, engineers & earth-lovers',
      tags: ['art', 'music', 'events'],
      description: 'A 16-person intentional community in a historic Victorian near Dolores Park — artists, writers, DJs, musicians, entrepreneurs, engineers, and scientists unified by a vision of inspired communal living. Weekly Monday dinners, live music, film series, hot tub and firepit out back.',
      funFact: 'Rotating cooking and cleaning duties keep the Victorian humming; monthly check-ins keep the humans humming.',
      events: [
        { title: 'House dinner', date: 'every Monday', kind: 'event', detail: 'Participatory community dinners with rotating cooking and cleaning shifts.', url: 'https://www.agapesf.org' },
      ],
      links: [
        { label: 'agapesf.org', url: 'https://www.agapesf.org/' },
        { label: 'instagram', url: 'https://www.instagram.com/agapeandfriends/' },
      ],
    },
    {
      id: 'embassy', name: 'The Embassy', emoji: '🏛️',
      neighborhood: 'Hayes Valley', lat: 37.775, lng: -122.429, coordsApprox: true,
      residents: 18, founded: 2012, status: 'active', inHSC: 'yes',
      vibe: 'governance lab & radical research',
      tags: ['tech', 'justice', 'governance'],
      description: 'A 1900 mansion and flagship of the international Embassy Network (co-founded by former NASA scientists). Residents prototype alternative governance and justice systems, host formerly incarcerated community members, and run the house by doocracy.',
      funFact: 'The Embassy Network spans houses across North America, Latin America, and Europe — this is where it started.',
      links: [
        { label: 'embassynetwork.com', url: 'https://embassynetwork.com/' },
        { label: 'archive', url: 'https://www.haight.place/Embassy/' },
      ],
    },
    {
      id: 'rgb', name: 'RGB House', emoji: '🌈',
      neighborhood: 'Lower Haight', lat: 37.772, lng: -122.431, coordsApprox: true,
      residents: 11, founded: 2015, status: 'active', inHSC: 'yes',
      vibe: 'art shows, lectures & slackocracy',
      tags: ['art', 'events'],
      description: 'Eleven long-term residents in a 3,100 sq ft Victorian — 9 bedrooms, 4 bathrooms, 3 living rooms — governed through a playful mix of doocracy, adhocracy, and "Slackocracy." Hosts art shows and lecture series.',
      funFact: 'Monthly dues of ~$255 cover food, utilities, cleaning, and events for the whole house.',
      links: [
        { label: 'rgb-house.com', url: 'https://www.rgb-house.com/' },
        { label: 'supernuclear case study', url: 'https://supernuclear.substack.com/p/case-study-the-story-of-rgb-2c0974654cde' },
      ],
    },
    {
      id: 'manzanita', name: 'Manzanita', emoji: '🌿',
      neighborhood: 'Outer Richmond', lat: 37.767, lng: -122.457, coordsApprox: true,
      residents: 12, founded: 2016, status: 'active', inHSC: 'yes',
      vibe: 'radical self-love & sustainability',
      tags: ['wellness'],
      description: 'A twelve-resident community built on radical self-love, kindness, curiosity, and environmental sustainability, with radical inclusion as a core value.',
      events: [
        { title: 'Garden gatherings', date: 'ongoing', kind: 'event', detail: 'Yoga, acro, and parties in the garden space.', url: 'https://haight-st-commons.org/projects' },
      ],
      links: [],
    },
    {
      id: 'beacon', name: 'Beacon House', emoji: '🔆',
      neighborhood: 'Mission', lat: 37.751, lng: -122.410, coordsApprox: true,
      residents: 8, foundedEst: 2016, status: 'active', inHSC: 'yes',
      vibe: 'cooperation, honesty & playful agency',
      tags: ['wellness'],
      description: 'Eight residents (25–33) living by values of cooperation, sharing, integrity, growth, and playful autonomy. Twice-weekly dinners and tri-weekly house meetings.',
      links: [],
    },
    {
      id: 'twentymish', name: '20mish', emoji: '🖥️',
      neighborhood: 'Mission', lat: 37.759, lng: -122.419, coordsApprox: true,
      residents: 40, founded: 2012, status: 'active', inHSC: 'maybe',
      vibe: 'hacker house turned creative village',
      tags: ['tech', 'hacker'],
      description: 'A 40-bedroom co-living building at 20th & Mission (Walk Score 99), founded in 2012 as the first crypto hacker house. Now home to AI engineers, designers, founders, scientists, chefs, and social workers, with a co-working office, media room, and courtyard.',
      funFact: '3 blocks from Dolores Park, 2 from Noisebridge, 4 from BART.',
      links: [
        { label: '20mish.com', url: 'https://20mish.com/' },
        { label: 'twitter', url: 'https://x.com/20mish_sf' },
      ],
    },
    {
      id: 'chaortica', name: 'Chaortica', emoji: '🌀',
      neighborhood: 'Ashbury Heights', lat: 37.769, lng: -122.447, coordsApprox: true,
      residents: 8, foundedEst: 2015, status: 'active', inHSC: 'yes',
      vibe: 'silly, radical, flat as a pancake',
      tags: ['art'],
      description: 'A community of radical, ambitious, inquisitive humans in a century-old house with a garden and greenhouse near the Haight-Ashbury crossroads. Governance is consensus and do-ocracy with a hard commitment to flatness — no member has more authority than any other.',
      funFact: 'Their membership agreement lives in a public GitHub repo.',
      events: [
        { title: 'Concerts & food gatherings', date: 'ongoing', kind: 'event', detail: 'House concerts and community meals in the garden.', url: 'https://haight-st-commons.org' },
      ],
      links: [
        { label: 'github', url: 'https://github.com/jtschoonhoven/chaortica' },
      ],
    },
    {
      id: 'template', name: 'Template House', emoji: '✊',
      neighborhood: 'Lower Haight', lat: 37.773, lng: -122.427, coordsApprox: true,
      residents: 5, foundedEst: 2020, status: 'active', inHSC: 'yes',
      vibe: 'second chances & solidarity',
      tags: ['justice'],
      description: 'Five residents exploring co-creation and solidarity in a substance- and weapon-free space. Home of the Second Life community for formerly incarcerated people, with a semi-public community living room that hosts "Revolution Sunday."',
      links: [
        { label: 'second life project', url: 'https://www.secondlifeproject.net/spaces' },
      ],
    },
    {
      id: 'readingroom', name: 'The Radical Reading Room', emoji: '📚',
      neighborhood: 'Lower Haight', address: '438 Haight St',
      lat: 37.7722, lng: -122.4297, coordsApprox: false,
      residents: null, founded: 2021, status: 'active', inHSC: 'yes',
      vibe: 'the quietest room in the commons',
      tags: ['events', 'community space'],
      description: 'Not a house but the network\'s public living room: a 700 sq ft free space on Haight St for quiet reading, writing, and study, run by volunteers at no charge. No talking, no calls, no meetings — but free jam sessions, reading groups, and watch parties after hours. (Public venue, so the pin is exact.)',
      links: [
        { label: 'theradicalreadingroom.org', url: 'https://theradicalreadingroom.org/' },
      ],
    },
    {
      id: 'kaleidoscope', name: 'Kaleidoscope', emoji: '🎨',
      neighborhood: 'Mission', lat: 37.757, lng: -122.416, coordsApprox: true,
      residents: 9, foundedEst: 2017, status: 'active', inHSC: 'yes',
      vibe: 'art, dance & emotional connection',
      tags: ['art', 'music', 'events'],
      description: 'Nine people focused on art, music, and dance in a 7-room house in the heart of the Mission. Clothing swaps, art nights, dinner parties, dance parties — and a deliberate culture of community care, vulnerability, and emotional connection.',
      links: [
        { label: 'website', url: 'https://sites.google.com/view/kscomission' },
      ],
    },
    {
      id: 'crest', name: 'Crest', emoji: '⛰️',
      neighborhood: 'Lower Haight', lat: 37.771, lng: -122.433, coordsApprox: true,
      residents: 10, foundedEst: 2018, status: 'active', inHSC: 'yes',
      vibe: 'self-development & diversity',
      tags: ['wellness'],
      description: 'Nine to ten residents prioritizing self-development, diversity, and a mission-driven, cooperative orientation.',
      links: [],
    },
    {
      id: 'chrysalis', name: 'Chrysalis', emoji: '🦋',
      neighborhood: 'Berkeley', lat: 37.872, lng: -122.273, coordsApprox: true,
      residents: 15, foundedEst: 2021, status: 'active', inHSC: 'yes',
      vibe: 'a home for life transitions',
      tags: ['family', 'co-parenting'],
      description: 'A fifteen-person intergenerational community in Berkeley for people in major life transitions — career changes, parenthood, new ventures. Family-style living with regular shared meals among technologists, parents, artists, scientists, teachers, and comedians.',
      links: [
        { label: 'chrysalisberkeley.com', url: 'https://chrysalisberkeley.com/' },
      ],
    },
    {
      id: 'realhouse', name: 'The Real House', emoji: '🍄',
      neighborhood: 'Alamo Square', lat: 37.776, lng: -122.437, coordsApprox: true,
      residents: null, founded: 2019, status: 'active', inHSC: 'yes',
      vibe: 'psychedelic, vivacious, real',
      tags: ['wellness', 'events'],
      description: 'Founded May 2019 as a space to "get real" with loving community. A vivacious, psychedelic, intentional home two blocks from Alamo Square, with a garden of apple trees, plum trees, and blackberries. Hosts Hippie Happy Hours, Sad Parties, Yoga Nidra, and acro yoga.',
      funFact: 'Yes, "Sad Parties" is a recurring event, and reportedly a great one.',
      links: [],
    },
    {
      id: 'grammys', name: "Grammy's House", emoji: '🐔',
      neighborhood: 'Inner Richmond', lat: 37.774, lng: -122.467, coordsApprox: true,
      residents: 7, founded: 2011, status: 'active', inHSC: 'yes',
      vibe: 'crafting, cooking & cozying',
      tags: ['music', 'events'],
      description: 'Seven humans, two friendly felines, and three friendly hens crafting, cooking, and cozying since 2011. Monthly living-room concerts (Groupmuse regulars), potlucks, fundraisers, and skillshares.',
      funFact: 'The hens are considered members.',
      events: [
        { title: 'Groupmuse house concerts', date: 'monthly', kind: 'event', detail: 'Classical musicians play the back porch under twinkling lights.', url: 'https://www.groupmuse.com/events/6709-grammy-s-house-groupmuse' },
      ],
      links: [
        { label: 'instagram', url: 'https://www.instagram.com/grammyshousecoop/' },
        { label: 'facebook', url: 'https://www.facebook.com/grammys.house.coop/' },
      ],
    },
    {
      id: 'nuhaus', name: 'NuHaus', emoji: '🔥',
      neighborhood: 'Alamo Square', lat: 37.775, lng: -122.434, coordsApprox: true,
      residents: 11, founded: 2016, status: 'active', inHSC: 'yes',
      vibe: 'intentionally unintentional',
      tags: ['burner', 'art'],
      description: 'Eleven people in a Victorian near Alamo Square, founded January 2016 by a crew leaving warehouse living. "Intentionally unintentional or unintentionally intentional, depending on who you ask" — kind, chill, crafty, Burner-y, allergic to mandatory structure.',
      links: [
        { label: 'facebook', url: 'https://www.facebook.com/onesixtwoone/' },
      ],
    },
    {
      id: 'village', name: 'The Village', emoji: '🧒',
      neighborhood: 'Panhandle', lat: 37.766, lng: -122.453, coordsApprox: true,
      residents: 19, founded: 2022, status: 'active', inHSC: 'maybe',
      vibe: 'raising kids together, not alone',
      tags: ['family', 'co-parenting'],
      description: 'A multigenerational co-living home of ~15 adults and 4 kids across three vertically-stacked units near the Panhandle. Non-hierarchical decision-making with equal say for every adult; a flagship Supernuclear case study in turning single-family housing into harmonious coliving.',
      links: [
        { label: 'villagehousesf.org', url: 'https://villagehousesf.org/the-residents' },
        { label: 'supernuclear case study', url: 'https://supernuclear.substack.com/p/case-study-the-village-san-francisco' },
      ],
    },
    {
      id: 'eucalyptus', name: 'Eucalyptus', emoji: '🌳',
      neighborhood: 'Panhandle', lat: 37.772, lng: -122.446, coordsApprox: true,
      residents: null, foundedEst: 2016, status: 'active', inHSC: 'yes',
      vibe: 'diverse professionals, many hobbies',
      tags: ['events'],
      description: 'A community of late-twenties to mid-thirties residents by the Panhandle, with a deliberately wide mix of professions and hobbies.',
      events: [
        { title: 'Seeking a housemate', date: '2026-06', kind: 'open room', detail: 'Listed one open room as of June 2026.', url: 'https://www.facebook.com/eucalyptushaus/' },
      ],
      links: [
        { label: 'facebook', url: 'https://www.facebook.com/eucalyptushaus/' },
      ],
    },
    {
      id: 'muse', name: 'The Muse', emoji: '🎭',
      neighborhood: 'NoPa', lat: 37.777, lng: -122.444, coordsApprox: true,
      residents: 13, foundedEst: 2015, status: 'active', inHSC: 'yes',
      vibe: 'low-key home, high-key parties',
      tags: ['art', 'events'],
      description: 'A 13-bedroom, 6.5-bath Victorian with residents mid-20s to mid-30s and minimal hard rules. Hobbies run from volleyball and fusion dance to 3D printing and immersive art; their Spring Bacchanalia made the SF Standard.',
      events: [
        { title: 'Spring Bacchanalia', date: 'annual', kind: 'event', detail: 'The house\'s legendary spring party, covered by the SF Standard.', url: 'https://sfstandard.com/2024/03/19/the-muse-sf-spring-bacchanalia-party/' },
      ],
      links: [],
    },
    {
      id: 'mcallister', name: 'McAllister House', emoji: '🏡',
      neighborhood: 'NoPa', lat: 37.778, lng: -122.439, coordsApprox: true,
      residents: 13, foundedEst: 2017, status: 'active', inHSC: 'yes',
      vibe: 'fun-loving weekly-dinner crew',
      tags: ['events'],
      description: 'Thirteen residents, mid-twenties to mid-thirties, with weekly dinners and occasional larger community events.',
      links: [],
    },
    {
      id: 'atrium', name: 'Atrium', emoji: '🪴',
      neighborhood: 'NoPa', lat: 37.777, lng: -122.441, coordsApprox: true,
      residents: null, foundedEst: 2019, status: 'active', inHSC: 'yes',
      vibe: 'warmth, connection & natural light',
      tags: ['wellness'],
      description: 'Community living self-described as "nicer, cleaner, and more spacious than your typical SF group house," valuing connection, warmth, and multi-generational community.',
      links: [],
    },
    {
      id: 'soa', name: 'Start of Anything', emoji: '🌱',
      neighborhood: 'Mission', lat: 37.760, lng: -122.418, coordsApprox: true,
      residents: 7, founded: 2022, status: 'active', inHSC: 'yes',
      vibe: 'science, AI & fifty potted plants',
      tags: ['tech'],
      description: 'Seven residents working across science, engineering, event planning, government, AI, and healthcare. The house keeps roughly 50 potted plants alive, which may be the most impressive collaboration of all.',
      links: [],
    },
    {
      id: 'thalia', name: 'Thalia', emoji: '✨',
      neighborhood: 'NoPa', lat: 37.776, lng: -122.441, coordsApprox: true,
      residents: 12, founded: 2024, status: 'active', inHSC: 'yes',
      vibe: 'joy, generosity & abundance',
      tags: ['wellness'],
      description: 'One of the network\'s newest houses (October 2024), centered on warmth and "energetic home-making": belonging, virtuous cycles of generosity, clear and empathetic communication, and beautification. Members from around the world; hot tub and firepit included.',
      links: [],
    },
    {
      id: 'treehouse', name: 'Treehouse', emoji: '🌲',
      neighborhood: 'Hayes Valley', lat: 37.776, lng: -122.424, coordsApprox: true,
      residents: 19, foundedEst: 2020, status: 'active', inHSC: 'yes',
      vibe: 'trauma-informed co-parenting',
      tags: ['family', 'co-parenting', 'justice'],
      description: 'Thirteen adults and six children across three interconnected units, focused on co-parenting — including fostering — and trauma-informed living: authentic, liberated, loving, resilient, sustainable.',
      links: [],
    },
    {
      id: 'heartloom', name: 'Heartloom', emoji: '🧵',
      neighborhood: 'North Berkeley', lat: 37.885, lng: -122.259, coordsApprox: true,
      residents: 20, founded: 2022, status: 'active', inHSC: 'yes',
      vibe: 'hearts interwoven on a loom',
      tags: ['queer', 'art'],
      description: 'Founded early 2022 in the North Berkeley hills — now 20+ healers, artists, and mystics across a two-story, 10-bedroom home. An LGBTQIA+-friendly space oriented toward creation and engagement with the world: the heart is care for each other, the loom is the interweaving of aspirations.',
      links: [],
    },
    {
      id: 'sigil', name: 'Sigil House', emoji: '🔮',
      neighborhood: 'Lower Haight', lat: 37.773, lng: -122.429, coordsApprox: true,
      residents: 5, foundedEst: 2021, status: 'active', inHSC: 'yes',
      vibe: 'transformation & alternative justice',
      tags: ['justice'],
      description: 'A five-bedroom Lower Haight house where three returning citizens and two never-incarcerated housemates live as one autonomous community built around transformation, empowerment, and alternative justice — a sister house to Template.',
      links: [
        { label: 'second life project', url: 'https://www.secondlifeproject.net/spaces' },
      ],
    },
    {
      id: 'presidio', name: 'Presidio Mansion', emoji: '🐕',
      neighborhood: 'Presidio', lat: 37.798, lng: -122.465, coordsApprox: true,
      residents: 6, foundedEst: 2018, status: 'active', inHSC: 'yes',
      vibe: 'four houses, one community',
      tags: ['events'],
      description: 'Six residents plus a dog in a large Victorian with a sun room, grand foyer, and a massive entertainment room — part of a four-house cluster of 25+ people.',
      events: [
        { title: 'Groupmuse piano night', date: '2026-06-05', kind: 'event', detail: 'Pianist Daniel Anastasio played "Patterns, Sequence, Recall" in the living room.', url: 'https://www.groupmuse.com/events/16655/early-access/' },
      ],
      links: [],
    },
    {
      id: 'centersf', name: 'The Center SF', emoji: '🍵',
      neighborhood: 'Lower Haight', address: '548 Fillmore St',
      lat: 37.7724, lng: -122.4304, coordsApprox: false,
      residents: 25, foundedEst: 2013, closedYear: 2025, status: 'closed', inHSC: 'maybe',
      vibe: 'tea house, yoga & ecstatic dance',
      tags: ['wellness', 'events', 'spiritual'],
      description: 'A decade-old teahouse, events space, and 19-room co-living hub for artists, Burners, bodyworkers, and techies — yoga, ecstatic dance, authentic relating. Closed June 2025 after city enforcement and leadership disputes; the community is resurrecting itself as the nonprofit Gather SF.',
      events: [
        { title: 'Gather SF pop-up tea lounge', date: '2026-07-28', kind: 'event', detail: 'The resurrected community hosts pop-up tea gatherings while hunting for a permanent space.', url: 'https://www.gathersf.org/events' },
        { title: 'Decentered open mic', date: '2026-08-04', kind: 'event', detail: 'Open mic by the Gather SF community, heir to The Center\'s stage.', url: 'https://www.gathersf.org/events' },
      ],
      links: [
        { label: 'thecentersf.com', url: 'https://www.thecentersf.com/' },
        { label: 'gather sf story', url: 'https://sfstandard.com/2025/09/16/the-center-resurrects-as-gather-sf-teahouse-community-hub/' },
      ],
    },
    {
      id: 'convent', name: 'The Convent', emoji: '⛪',
      neighborhood: 'Lower Haight', lat: 37.773, lng: -122.430, coordsApprox: true,
      residents: 24, foundedEst: 2015, status: 'active', inHSC: 'maybe',
      vibe: 'an art collective in a former rectory',
      tags: ['art', 'music', 'events'],
      description: 'A three-story former rectory at Fillmore & Oak housing 24 artists across creative disciplines — 19 bedrooms, a healing sanctuary, a chapel, a recording studio, and a tea house in the basement.',
      funFact: 'Yes, there is a real chapel, and yes, it hosts shows.',
      links: [
        { label: 'theconventarthouse.com', url: 'https://www.theconventarthouse.com/' },
      ],
    },
    {
      id: 'mushrooms', name: 'Thriving Mushrooms', emoji: '🍄‍🟫',
      neighborhood: 'Noe Valley', lat: 37.744, lng: -122.437, coordsApprox: true,
      residents: null, foundedEst: 2019, status: 'unknown', inHSC: 'yes',
      vibe: 'mindfulness, play & planet justice',
      tags: ['wellness', 'spiritual'],
      description: 'An intentional community anchored in self-growth and mutual support, organizing life around four pillars: Mindfulness & Healing, Playfulness, Art & Creativity, and Social & Planet Justice.',
      links: [],
    },
    {
      id: 'rabbithole', name: 'The Rabbithole', emoji: '🐇',
      neighborhood: 'Glen Park', lat: 37.739, lng: -122.452, coordsApprox: true,
      residents: 14, foundedEst: 2024, status: 'active', inHSC: 'yes',
      vibe: 'kind, playful & delightfully odd',
      tags: ['art'],
      description: 'An experiment in a better way to live, started by Andrew and Priya: ~14 residents in a French Victorian mansion affiliated with the Embassy Network, cultivating a uniquely kind, playful, odd community with short- and long-term rooms.',
      events: [
        { title: 'Supernuclear case study', date: '2025', kind: 'press', detail: 'The story of how Rabbithole came together, in Supernuclear.', url: 'https://supernuclear.substack.com/p/the-story-of-rabbithole-case-study' },
      ],
      links: [
        { label: 'embassy network', url: 'https://embassynetwork.com' },
      ],
    },
    {
      id: 'archive', name: 'The Archive', emoji: '🗄️',
      neighborhood: 'Mission Dolores', lat: 37.761, lng: -122.425, coordsApprox: true,
      residents: null, foundedEst: 2014, status: 'unknown', inHSC: 'yes',
      vibe: 'quietly legendary',
      tags: ['tech'],
      description: 'A long-running group house in the Mission Dolores area, listed in the Haight Street Commons directory. Details are scarce by design — some houses prefer the quiet life.',
      links: [],
    },
    {
      id: 'manor', name: 'The Manor of Being', emoji: '🧘',
      neighborhood: 'Mission', lat: 37.756, lng: -122.413, coordsApprox: true,
      residents: null, foundedEst: 2018, status: 'unknown', inHSC: 'yes',
      vibe: 'being, in manor form',
      tags: ['spiritual'],
      description: 'An intentional community in the Mission listed in the Haight Street Commons directory; the name promises a lot and the house keeps the rest mysterious.',
      links: [],
    },
    {
      id: 'livenearfriends', name: 'The Ashbury Compound', emoji: '🏘️',
      neighborhood: 'Ashbury Heights', lat: 37.764, lng: -122.439, coordsApprox: true,
      residents: 23, founded: 2019, status: 'active', inHSC: 'no',
      vibe: 'friend compound with an asterisk',
      tags: ['family', 'co-parenting'],
      description: 'A 12,610 sq ft compound of 8 interconnected apartments — 7 couples, 11 kids, 2 grandparents, shared garden and hot tub — that went viral as the model "friend compound." The asterisk: the building was cleared for them via Ellis Act evictions of 13 long-term low-income, elderly, and disabled tenants, a history the SF Standard surfaced in 2025.',
      events: [
        { title: 'Eviction history exposed', date: '2025-03', kind: 'press', detail: 'SF Standard investigation into the Ellis Act evictions behind the compound.', url: 'https://sfstandard.com/2025/03/09/san-francisco-friend-compound-eviction-secret/' },
      ],
      links: [],
    },
    {
      id: 'freedomwest', name: 'Freedom West Homes', emoji: '🗽',
      neighborhood: 'Fillmore', lat: 37.780, lng: -122.427, coordsApprox: true,
      residents: 700, founded: 1973, status: 'active', inHSC: 'no',
      vibe: 'Black-led co-op, 50 years strong',
      tags: ['justice', 'historical'],
      description: 'A 382-unit resident-owned housing cooperative founded in 1973 by Rev. J. Austell Hall to keep Black families in the Fillmore after redevelopment razed the neighborhood. Half a century later the co-op still stands — and is now driving its own $8B "Freedom West 2.0" redevelopment as owners, not displaced tenants.',
      funFact: 'One of the largest surviving legacies of Black cooperative ownership in San Francisco.',
      events: [
        { title: 'Freedom West 2.0 breaks ground', date: '2026', kind: 'update', detail: 'Demolition permits filed at 860-880 McAllister; first phase adds 115 affordable senior units.', url: 'https://sfyimby.com/2026/06/demolition-permits-filed-for-860-880-mcallister-street-san-francisco.html' },
      ],
      links: [
        { label: 'freedom west', url: 'https://www.freedomwesthomes.org/' },
      ],
    },

    /* ================= the wider modern scene ================= */
    {
      id: 'missioncontrol', name: 'Mission Control', emoji: '🚀',
      neighborhood: 'Mission', address: '2211 Mission St',
      lat: 37.7618, lng: -122.4193, coordsApprox: false,
      residents: 10, founded: 2013, closedYear: 2026, status: 'closed', inHSC: 'no',
      vibe: 'the OG hacker house',
      tags: ['tech', 'hacker'],
      description: 'A 10-room, 6,400 sq ft hacker house above Mission Street that ran for over a decade — famously housing the 2014 Thiel Fellow class. Alumni include Vitalik Buterin (Ethereum), Lucy Guo (Scale AI), and Marty Kausas (Pylon). Marked closed as of 2026.',
      funFact: 'Threw an "AI-simulated party" in 2024 that got SF Standard coverage — a very Mission Control way to go out.',
      links: [
        { label: 'sf standard', url: 'https://sfstandard.com/2024/05/04/mission-control-hacker-house-san-francisco-ai-simulated-party/' },
      ],
    },
    {
      id: 'langton', name: 'Langton Labs', emoji: '🧪',
      neighborhood: 'SoMa', address: '7-9 Langton St',
      lat: 37.7752, lng: -122.4062, coordsApprox: false,
      residents: 9, founded: 2007, closedYear: 2016, status: 'closed', inHSC: 'no',
      vibe: 'engineers instead of hippies',
      tags: ['tech', 'art', 'hacker'],
      description: 'A 6,000 sq ft former sign factory turned arts-and-science warehouse community (2007–2016): scientists, artists, engineers, and travelers in 9 bedrooms plus event space. Press called it "a millennial commune with engineers instead of hippies." Sold for $2.35M in 2016.',
      funFact: 'Subject of the 2021 documentary "The View from Langton Street."',
      links: [
        { label: 'socketsite', url: 'https://socketsite.com/archives/2020/04/millennial-commune-on-the-market-in-sf.html' },
      ],
    },
    {
      id: 'kerista', name: 'Kerista Commune', emoji: '💞',
      neighborhood: 'Cole Valley / Haight', lat: 37.7674, lng: -122.4498, coordsApprox: true,
      residents: 30, founded: 1971, closedYear: 1991, status: 'historical', inHSC: 'no',
      vibe: 'polyfidelity & Macintosh dealing',
      tags: ['historical', 'free love', 'tech'],
      description: 'The legendary 1971–1991 commune of Bro Jud and Eve Furchgott that coined the words "polyfidelity" and "compersion." Members practiced group marriage with nightly rotation schedules, shared all income — and funded it all by running Abacus, one of the biggest early Macintosh dealerships in the Bay.',
      funFact: 'A free-love commune that was also, improbably, a top Apple reseller of the 1980s.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kerista' },
        { label: 'kerista.com archive', url: 'https://www.kerista.com/' },
      ],
    },
    {
      id: 'radish', name: 'Radish', emoji: '🌶️',
      neighborhood: 'Oakland', lat: 37.804, lng: -122.271, coordsApprox: true,
      residents: 28, founded: 2020, status: 'active', inHSC: 'no',
      vibe: 'the friend-compound blueprint',
      tags: ['family', 'co-parenting'],
      description: 'An Oakland residential compound of 20 adults and 8 kids across mixed unit types, created by Supernuclear\'s Phil Levin and Kristen Berman. The model home of the "friend compound" movement — now splitting amoeba-style into three new East Bay compounds as the families grow.',
      events: [
        { title: 'The compound is for sale', date: '2026-06', kind: 'update', detail: 'The 14,000 sq ft compound listed as the community outgrows it; move-out by end of 2026.', url: 'https://www.buyradish.com' },
        { title: 'Three new compounds', date: '2026', kind: 'update', detail: 'Radish splits into two Berkeley compounds and one in Alameda via Live Near Friends.', url: 'https://supernuclear.substack.com/p/radish-is-officially-for-sale' },
      ],
      links: [
        { label: 'radishoakland.com', url: 'https://radishoakland.com/' },
      ],
    },
    {
      id: 'bsc', name: 'Berkeley Student Cooperative', emoji: '🎓',
      neighborhood: 'Berkeley', lat: 37.872, lng: -122.260, coordsApprox: true,
      residents: 1300, founded: 1933, status: 'active', inHSC: 'no',
      vibe: 'the co-op mothership',
      tags: ['students', 'historical'],
      description: 'The largest student housing cooperative in the United States: 1,300+ members across 20 houses around the UC Berkeley campus, born in the Great Depression and still run democratically, with every member contributing work hours to keep rent low.',
      funFact: 'Founded in 1933 — the oldest continuously-operating entry on this whole map.',
      events: [
        { title: 'Alumni Fun-Fest', date: 'annual', kind: 'event', detail: 'Free annual gathering of co-opers past and present.', url: 'https://bsc.coop/news-events/news' },
      ],
      links: [
        { label: 'bsc.coop', url: 'https://www.bsc.coop/' },
        { label: 'nasco', url: 'https://www.nasco.coop/' },
      ],
    },
    {
      id: 'struggle', name: 'Struggle Mountain', emoji: '🏔️',
      neighborhood: 'Los Altos Hills', lat: 37.367, lng: -122.120, coordsApprox: true,
      residents: 15, founded: 1966, status: 'active', inHSC: 'no',
      vibe: "the last '60s commune standing",
      tags: ['historical', 'family', 'music'],
      description: 'The Bay Area\'s last continuously-running 1960s-style commune: 10 adults and 5 kids on 10 acres above Palo Alto, community-owned since 1976. Named by Joan Baez, who lived there in the \'70s; Allen Ginsberg was a house guest.',
      funFact: 'Nearly 60 years old and still going — the elder of every commune on this map.',
      events: [
        { title: 'Room for rent', date: '2025', kind: 'open room', detail: 'The co-op occasionally lists rooms on ic.org.', url: 'https://www.ic.org/advert/bay-area-housing-cooperative-has-a-room-for-rent/' },
      ],
      links: [
        { label: 'ic.org directory', url: 'https://www.ic.org/directory/struggle-mountain/' },
      ],
    },

    /* ================= the 1960s–70s: the first wave ================= */
    {
      id: 'diggers', name: 'The Diggers / Free City', emoji: '🍞',
      neighborhood: 'Haight-Ashbury', lat: 37.7699, lng: -122.4460, coordsApprox: true,
      residents: 50, founded: 1966, closedYear: 1968, status: 'historical', inHSC: 'no',
      vibe: 'everything free, forever',
      tags: ['historical', 'justice', 'art'],
      description: 'Anarchist street-theater artists and mutual-aid pioneers of the Summer of Love: free food in the Panhandle every day at 4pm, Free Stores, free crash pads, free concerts, and happenings like the Death of Money Parade. Rebranded as the Free City Collective in 1967 before dissolving at the 1968 solstice. The spiritual ancestors of every free fridge and mutual-aid network in the city.',
      funFact: 'To get free stew you had to step through a giant yellow picture frame — the "Free Frame of Reference."',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/San_Francisco_Diggers' },
        { label: 'digger archives', url: 'https://www.diggers.org/free_city.htm' },
      ],
    },
    {
      id: 'kaliflower', name: 'Kaliflower Commune', emoji: '🌼',
      neighborhood: 'Western Addition → Mission', address: '1873 Sutter St, then 1209 Scott St, then Shotwell St',
      lat: 37.7857, lng: -122.4373, coordsApprox: true,
      residents: 15, founded: 1967, closedYear: 1974, status: 'historical', inHSC: 'no',
      vibe: 'free press & gay liberation',
      tags: ['historical', 'queer', 'free love'],
      description: 'The Sutter Street Commune — later "Friends of Perfection" — ran a Free Print Shop in the basement and a Free Bakery upstairs, and published the Kaliflower newsletter (1969–71), hand-delivered weekly to 300+ communes. It was the social network of the entire SF commune scene, bridging Digger free-ethics with early gay liberation, and it incubated the Cockettes.',
      funFact: 'Thursdays were "Kaliflower Day," the intercommunal delivery ritual that stitched the whole scene together.',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/Kaliflower_and_the_Dream_Continues' },
        { label: 'outhistory exhibit', url: 'https://outhistory.org/exhibits/show/kali/kaliintro' },
      ],
    },
    {
      id: 'goodearth', name: 'Good Earth Commune', emoji: '🌍',
      neighborhood: 'Haight-Ashbury', lat: 37.7697, lng: -122.4470, coordsApprox: true,
      residents: 200, founded: 1970, closedYear: 1975, status: 'historical', inHSC: 'no',
      vibe: 'the Haight\'s biggest family',
      tags: ['historical', 'justice'],
      description: 'A sprawling commune network founded by two ex-prisoners that at its peak claimed some 2,000 members across roughly nine buildings on Oak, Cole, Fell, Haight, and Central. Ex-cons, Vietnam vets, and runaways ran the neighborhood recycling center and Free Store, fought heroin dealers and redevelopment — and seeded the Food Conspiracy co-ops that fed 1,500+ households by 1975.',
      funFact: 'Its food-buying clubs outlived the commune itself, evolving into the People\'s Food System.',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/index.php?title=Communes_and_Housing' },
        { label: 'food conspiracy', url: 'https://www.foundsf.org/The_Food_Conspiracy' },
      ],
    },
    {
      id: 'cockettes', name: 'The Cockettes — "The Chateau"', emoji: '💄',
      neighborhood: 'Haight-Ashbury', address: '1965 Oak St',
      lat: 37.7716, lng: -122.4525, coordsApprox: false,
      residents: 12, founded: 1969, closedYear: 1972, status: 'historical', inHSC: 'no',
      vibe: 'glitter, drag & midnight musicals',
      tags: ['historical', 'queer', 'art'],
      description: 'Hibiscus\'s psychedelic drag-theater commune, born out of Kaliflower in fall 1969. Members lived across three decorated houses (including "The Chateau" on Oak Street, wild lavender in the yard) and staged legendary midnight musicals at the Palace Theater — gender-bending glitter theater that prefigured decades of queer performance.',
      funFact: 'Their free-theater ethic came straight from the Diggers; the glitter was all their own.',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/index.php?title=Cockettes' },
        { label: 'cockettes.com', url: 'https://www.cockettes.com/history/' },
      ],
    },
    {
      id: 'angelsoflight', name: 'Angels of Light', emoji: '👼',
      neighborhood: 'Haight-Ashbury', lat: 37.7710, lng: -122.4440, coordsApprox: true,
      residents: 15, founded: 1971, closedYear: 1988, status: 'historical', inHSC: 'no',
      vibe: 'free theater, freer glitter',
      tags: ['historical', 'queer', 'art'],
      description: 'When Hibiscus split from the Cockettes over charging admission, he founded the Angels of Light — a commune-based free theater troupe living across several houses, sewing lavish costumes by day and staging free spectacles by night. They carried the Kaliflower free-arts flame all the way to 1988.',
      links: [
        { label: 'digger archives', url: 'https://www.diggers.org/angels_of_light.htm' },
      ],
    },
    {
      id: 'oneworld', name: 'One World Family Commune', emoji: '🛸',
      neighborhood: 'Haight-Ashbury', lat: 37.7690, lng: -122.4530, coordsApprox: true,
      residents: 200, founded: 1967, closedYear: 1975, status: 'historical', inHSC: 'no',
      vibe: 'vegetarian food from galactic beings',
      tags: ['historical', 'spiritual'],
      description: 'Founded by UFO contactee Allen Michael around his macrobiotic restaurant "The Here and Now" at Haight & Stanyan. The commune practiced total sharing, wore robes, protested the war, and served vegetarian food "inspired by Galactic Beings" before relocating to Berkeley as the Haight declined.',
      funFact: 'Allen Michael claimed to channel Creative Intelligence from UFOs; the restaurant reviews were nonetheless solid.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/One_World_Family_Commune' },
      ],
    },
    {
      id: 'hoom', name: 'Holy Order of MANS', emoji: '✝️',
      neighborhood: 'Duboce Triangle', address: '20 Steiner St',
      lat: 37.7697, lng: -122.4333, coordsApprox: false,
      residents: 300, founded: 1967, closedYear: 1988, status: 'historical', inHSC: 'no',
      vibe: 'monastic counterculture',
      tags: ['historical', 'spiritual'],
      description: 'An esoteric Christian order headquartered at 20 Steiner St, founded by retired engineer Earl "Father Paul" Blighton to minister to spiritually-seeking hippies. Members took vows of poverty and service, pooled all earnings (a $2M common fund by 1972), ran the Brother Juniper\'s restaurants, and founded Raphael House — San Francisco\'s first family homeless shelter.',
      funFact: 'It evolved from hippie mysticism into an Orthodox Christian church — the rare commune that became a denomination.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Holy_Order_of_MANS' },
        { label: 'raphael house', url: 'https://www.raphaelhouse.org/about/history/' },
      ],
    },
    {
      id: 'hungadunga', name: 'Hunga Dunga — the Blue House', emoji: '🔵',
      neighborhood: 'Castro / Mission', address: '3841 18th St',
      lat: 37.7616, lng: -122.4307, coordsApprox: false,
      residents: 10, founded: 1971, closedYear: 1975, status: 'historical', inHSC: 'no',
      vibe: 'la maison bleue',
      tags: ['historical', 'art', 'music'],
      description: 'A blue Victorian commune named after a Marx Brothers gag, where French singer Maxime Le Forestier crashed in 1971 — and immortalized it in "San Francisco" ("C\'est une maison bleue…"), a song every French person can still sing. The house remains a pilgrimage site for French tourists.',
      funFact: 'The city repainted it blue in 2011 after Le Forestier fans complained it had gone green.',
      links: [
        { label: 'kalw story', url: 'https://www.kalw.org/arts-entertainment/2023-09-18/the-blue-house-in-san-francisco-that-captured-the-heart-of-the-french' },
      ],
    },
    {
      id: 'familydog', name: 'Family Dog Commune', emoji: '🐶',
      neighborhood: 'Pacific Heights', address: '2125 Pine St',
      lat: 37.7887, lng: -122.4355, coordsApprox: false,
      residents: 20, founded: 1965, closedYear: 1968, status: 'historical', inHSC: 'no',
      vibe: 'the dogs that invented the rock show',
      tags: ['historical', 'music'],
      description: 'The communal house whose residents — named "The Family Dog" after the landlord\'s permissive pet policy — threw the first San Francisco Dance Concerts in 1965. Chet Helms took the operation to the Avalon Ballroom, launching Big Brother with Janis Joplin and inventing the psychedelic poster-and-light-show concert as we know it.',
      funFact: 'They named their whole concert-promotion empire after the house dogs.',
      links: [
        { label: 'outside lands podcast', url: 'https://www.outsidelands.org/podcast/WNP467_The_Family_Dog' },
      ],
    },
    {
      id: 'dead710', name: '710 Ashbury — Grateful Dead House', emoji: '💀',
      neighborhood: 'Haight-Ashbury', address: '710 Ashbury St',
      lat: 37.7686, lng: -122.4460, coordsApprox: false,
      residents: 12, founded: 1966, closedYear: 1968, status: 'historical', inHSC: 'no',
      vibe: 'the psychedelic mothership',
      tags: ['historical', 'music', 'free love'],
      description: 'The Grateful Dead\'s communal home from fall 1966 to spring 1968, bankrolled by LSD chemist Owsley Stanley. The band lived, rehearsed, and held court here at the exact center of the Summer of Love — with the Hells Angels clubhouse directly across the street.',
      funFact: 'The famous October 1967 pot raid on the house made the cover of Rolling Stone\'s first-ever issue.',
      links: [
        { label: 'clio history', url: 'https://theclio.com/entry/15969' },
      ],
    },
    {
      id: 'angels719', name: '719 Ashbury — Hells Angels House', emoji: '🏍️',
      neighborhood: 'Haight-Ashbury', address: '719 Ashbury St',
      lat: 37.7687, lng: -122.4463, coordsApprox: false,
      residents: 10, founded: 1967, closedYear: 1985, status: 'historical', inHSC: 'no',
      vibe: 'outlaw neighbors of the Dead',
      tags: ['historical'],
      description: 'The San Francisco Hells Angels chapter house through the counterculture years — directly across the street from the Grateful Dead. Bikers and hippies made improbable neighbors, security partners, and occasional adversaries in the strangest block-level détente of the 1960s.',
      links: [
        { label: 'voicemap', url: 'https://voicemap.me/tour/san-francisco/haight-ashbury-tour-golden-gate-park-hippie-temptation-house/sites/hell-s-angels-and-the-grateful-dead-houses' },
      ],
    },
    {
      id: 'page1090', name: '1090 Page — Big Brother House', emoji: '🎸',
      neighborhood: 'Haight-Ashbury', address: '1090 Page St',
      lat: 37.7723, lng: -122.4391, coordsApprox: false,
      residents: 25, founded: 1965, closedYear: 1968, status: 'historical', inHSC: 'no',
      vibe: 'a ballroom in the basement',
      tags: ['historical', 'music'],
      description: 'A 22-room Victorian rooming house ($15/month!) whose redwood-paneled basement ballroom incubated the SF Sound: Big Brother and the Holding Company formed and rehearsed here, Janis Joplin lived communally here in 1966–67, and Quicksilver Messenger Service and Sopwith Camel both got their start in the same basement.',
      funFact: 'Possibly the highest bands-per-square-foot of any basement in American history.',
      links: [
        { label: 'rock & roll roadmap', url: 'https://rockandrollroadmap.com/places/hotels-motels/san-francisco-area-hotels-motels/albin-rooming-house-big-brother-and-the-holding-company-began-here/' },
      ],
    },
    {
      id: 'fulton2400', name: '2400 Fulton — Jefferson Airplane Mansion', emoji: '✈️',
      neighborhood: 'Inner Richmond', address: '2400 Fulton St',
      lat: 37.7763, lng: -122.4573, coordsApprox: false,
      residents: 10, founded: 1968, closedYear: 1985, status: 'historical', inHSC: 'no',
      vibe: 'a mansion painted black',
      tags: ['historical', 'music'],
      description: 'Jefferson Airplane bought this 17-room 1904 mansion facing Golden Gate Park for $70,000 in 1968, painted the whole thing black, and turned the basement into a recording studio. Band, crew, and an ever-rotating cast of the scene lived among the mahogany paneling and eight fireplaces.',
      funFact: 'The band titled their 1990 compilation album "2400 Fulton Street" after the house.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/2400_Fulton_Street' },
        { label: 'outside lands podcast', url: 'https://www.outsidelands.org/podcast/WNP556_2400_Fulton_Jefferson_Airplane_House' },
      ],
    },
    {
      id: 'manson636', name: '636 Cole — Manson\'s SF House', emoji: '⚠️',
      neighborhood: 'Cole Valley', address: '636 Cole St',
      lat: 37.7690, lng: -122.4506, coordsApprox: false,
      residents: 8, founded: 1967, closedYear: 1967, status: 'historical', inHSC: 'no',
      vibe: 'the dark footnote',
      tags: ['historical'],
      description: 'Charles Manson lived here April–November 1967 with the earliest members of what became the Family, recruiting drifting young seekers at the height of the Summer of Love. Included on this map as the sobering counterweight: the same open communal culture that built free bakeries could also be exploited.',
      links: [
        { label: 'hoodline', url: 'https://hoodline.com/2014/10/introducing-the-haight-s-charles-manson-house/' },
      ],
    },
    {
      id: 'willard', name: 'Willard Street Commune', emoji: '🕯️',
      neighborhood: 'Cole Valley / Parnassus', lat: 37.7643, lng: -122.4553, coordsApprox: true,
      residents: null, founded: 1970, closedYear: 1974, status: 'historical', inHSC: 'no',
      vibe: 'queer commune of the Kaliflower web',
      tags: ['historical', 'queer'],
      description: 'One of the queer-identified communes documented in OutHistory\'s Kaliflower exhibit — part of the intercommunal free network that traded bread, print runs, and ideas across the city. Little else survives in the record, which is exactly why it\'s here.',
      links: [
        { label: 'outhistory exhibit', url: 'https://outhistory.org/exhibits/show/kali/kaliintro' },
      ],
    },
    {
      id: 'castro529', name: '529 Castro Street Commune', emoji: '🏳️‍🌈',
      neighborhood: 'Castro', address: '529 Castro St',
      lat: 37.7599, lng: -122.4350, coordsApprox: false,
      residents: 8, founded: 1970, closedYear: 1975, status: 'historical', inHSC: 'no',
      vibe: 'gay communalism, before the Castro was the Castro',
      tags: ['historical', 'queer'],
      description: 'A documented early queer commune from the era when thousands of gay hippies were moving into cheap Castro Victorians — communal housing experiments that helped transform the neighborhood into the world\'s most famous gayborhood.',
      links: [
        { label: 'outhistory exhibit', url: 'https://outhistory.org/exhibits/show/kali/kaliintro' },
        { label: 'foundsf: the castro', url: 'https://www.foundsf.org/index.php?title=The_Castro%3A_The_Rise_of_a_Gay_Community' },
      ],
    },
    {
      id: 'hearthshire', name: 'Hearthshire & Hearth School', emoji: '🧸',
      neighborhood: 'Outer Sunset', lat: 37.7549, lng: -122.4916, coordsApprox: true,
      residents: 15, founded: 1969, closedYear: 1976, status: 'historical', inHSC: 'no',
      vibe: 'commune with its own school',
      tags: ['historical', 'family'],
      description: 'A communal household that ran its own alternative school for the children of the commune movement — shared parenting, collective decision-making, and pedagogical experimentation, documented in the Digger archives.',
      links: [
        { label: 'digger archives', url: 'https://www.diggers.org/hearth.html' },
      ],
    },
    {
      id: 'projectone', name: 'Project One', emoji: '🏭',
      neighborhood: 'SoMa', address: '1380 Howard St',
      lat: 37.7742, lng: -122.4137, coordsApprox: false,
      residents: 200, founded: 1970, closedYear: 1980, status: 'historical', inHSC: 'no',
      vibe: "SF's first warehouse community",
      tags: ['historical', 'art', 'tech'],
      description: 'An 84,000 sq ft abandoned candy factory turned into San Francisco\'s first warehouse community: artists, filmmakers, technologists, an alternative high school, and KPOO community radio, governed by weekly consensus meetings and nothing else.',
      funFact: 'Housed Resource One, whose Community Memory Project (1973) ran the first public computer bulletin board — the commune movement accidentally prototyped the internet forum.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Project_One_(San_Francisco)' },
        { label: 'foundsf', url: 'https://www.foundsf.org/Project_One_Warehouse' },
      ],
    },
    {
      id: 'redvic', name: 'The Red Victorian', emoji: '❤️',
      neighborhood: 'Upper Haight', address: '1665 Haight St',
      lat: 37.7696, lng: -122.4503, coordsApprox: false,
      residents: 20, founded: 1977, closedYear: 2022, status: 'closed', inHSC: 'maybe',
      vibe: 'peace, love & queer art hotel',
      tags: ['queer', 'art', 'historical'],
      description: 'The 1904 Jefferson Hotel became the "Jeffrey Haight" in 1967, then peace activist Sami Sunchild painted it red in 1977 and ran it as a peace-conversation B&B for 36 years. It later became an Embassy Network co-living house and home of the Fishbowl Collective of trans and QTPOC artists, before the building sold in 2022.',
      funFact: 'Hosted weekly "World Peace Conversations" in the ground-floor parlor for over three decades.',
      events: [
        { title: 'Renovation underway', date: '2025-2026', kind: 'update', detail: 'The building, vacant since the 2022 sale, is under interior renovation — next chapter unknown.', url: 'https://sf.gazetteer.co/resurrecting-the-red-vic' },
      ],
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/The_Red_Victorian' },
        { label: 'history blog', url: 'https://redvichistory.wordpress.com/' },
      ],
    },
    {
      id: 'ubuntu', name: 'Chateau Ubuntu', emoji: '🏰',
      neighborhood: 'Alamo Square', address: '860 Fell St',
      lat: 37.7743, lng: -122.4330, coordsApprox: false,
      residents: 38, founded: 2015, closedYear: 2020, status: 'closed', inHSC: 'maybe',
      vibe: '"I am because you are"',
      tags: ['events', 'wellness'],
      description: 'A historic 10-bedroom 1894 mansion on Fell St that housed up to 38 people under the Ubuntu philosophy — shared meals, gratitude circles, radical acceptance, and yes, cuddle puddles. The Planning Department cited it for illegal occupancy in 2017 and the experiment eventually wound down.',
      funFact: 'Its governance experiments influenced the houses that came after it.',
      links: [
        { label: 'sfist coverage', url: 'https://sfist.com/2017/01/26/uhoh_chateau_ubuntu/' },
      ],
    },
    {
      id: 'olompali', name: 'Olompali — The Chosen Family', emoji: '🐎',
      neighborhood: 'Novato (Marin)', lat: 38.1525, lng: -122.5713, coordsApprox: true,
      residents: 37, founded: 1967, closedYear: 1969, status: 'historical', inHSC: 'no',
      vibe: '690 acres of utopia',
      tags: ['historical', 'free love', 'music'],
      description: 'Don McCoy\'s 690-acre ranch commune north of Novato: a 22-room mansion, horses, a pool, an on-site school, and an outdoor oven baking hundreds of loaves twice a week for the Diggers\' free food lines. The Dead, Joplin, and Santana all passed through before fire, raids, and tragedy ended it in 1969. Now a state park.',
      funFact: 'An Olompali photo is on the back cover of the Grateful Dead\'s "Aoxomoxoa."',
      links: [
        { label: 'olompali state park', url: 'https://www.parks.ca.gov/?page_id=22728' },
        { label: 'history', url: 'https://bammers.wordpress.com/2020/11/25/olompali-a-60s-commune/' },
      ],
    },
    {
      id: 'morningstar', name: 'Morningstar Ranch', emoji: '☀️',
      neighborhood: 'Occidental (Sonoma)', lat: 38.3736, lng: -122.6378, coordsApprox: true,
      residents: 150, founded: 1966, closedYear: 1971, status: 'historical', inHSC: 'no',
      vibe: 'open land, denied to no one',
      tags: ['historical', 'free love'],
      description: 'Lou Gottlieb\'s 31-acre open-land commune an hour north of the city, run on the principle "Land Access To Which Is Denied No One." Drew 150+ residents at its peak and served as the country retreat for the Haight scene — until Sonoma County bulldozed the structures.',
      funFact: 'Gottlieb (of the Limeliters) tried to deed the land to God; the county assessor declined.',
      links: [
        { label: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Morningstar_Commune' },
      ],
    },
    {
      id: 'wallerstreet', name: 'Waller Street Community', emoji: '🛋️',
      neighborhood: 'Lower Haight', lat: 37.772, lng: -122.430, coordsApprox: true,
      residents: 6, foundedEst: 2021, status: 'active', inHSC: 'no',
      vibe: 'porch coffee & shared groceries',
      tags: ['family', 'co-parenting'],
      description: 'An intentional TIC community on a double-wide Lower Haight lot — currently 4 adults and 2 kids across two units, with Monday dinners, shared grocery runs, baby-monitor swaps, and stoop coffee culture. Recruiting neighbors to buy the third unit.',
      events: [
        { title: 'Third unit open', date: 'fall 2026', kind: 'open room', detail: 'Seeking new co-owners to join the community, via Supernuclear classifieds.', url: 'https://supernuclear.substack.com/p/supernuclear-classifieds-5' },
      ],
      links: [
        { label: 'supernuclear classifieds', url: 'https://supernuclear.substack.com/p/supernuclear-classifieds-5' },
      ],
    },

    /* ================= housing co-ops: the institutional layer ================= */
    {
      id: 'stfrancissq', name: 'St. Francis Square', emoji: '🤝', kind: 'coop',
      neighborhood: 'Western Addition', address: 'Bertie Minor Ln (Geary & Webster)',
      lat: 37.7827, lng: -122.4343, coordsApprox: false,
      residents: 299, founded: 1963, status: 'active', inHSC: 'no',
      vibe: 'the union-built original',
      tags: ['justice', 'historical'],
      description: 'Built in 1963 by the ILWU longshoremen\'s union: 299 co-op apartments in twelve walk-ups around landscaped courtyards (Lawrence Halprin did the landscape). Deliberately integrated from day one, it proved worker-owned affordable housing could work in SF — two years before this map\'s timeline even starts.',
      funFact: 'Sponsored by the same union that shut down the port in the 1934 General Strike.',
      links: [
        { label: 'sfsquarecoop.com', url: 'https://sfsquarecoop.com/' },
        { label: 'foundsf', url: 'https://www.foundsf.org/Building_the_St._Francis_Community' },
      ],
    },
    {
      id: 'artaud', name: 'Project Artaud', emoji: '🎪', kind: 'coop',
      neighborhood: 'Mission', address: '499 Alabama St',
      lat: 37.7648, lng: -122.4103, coordsApprox: false,
      residents: 100, founded: 1971, status: 'active', inHSC: 'no',
      vibe: 'the artists who bought the factory',
      tags: ['art', 'historical'],
      description: 'In 1971 artists occupied the abandoned 100,000 sq ft American Can Company factory and never left — today it\'s a member-run co-op of 79 live-work spaces for 100+ painters, dancers, and musicians, with four theaters and a gallery inside. Named for Antonin Artaud; the legal template for SF\'s live-work ordinance.',
      funFact: 'Z Space and Theatre of Yugen still perform inside what is technically their landlords\' home.',
      links: [
        { label: 'projectartaud.org', url: 'https://projectartaud.org/' },
      ],
    },
    {
      id: 'marcusgarvey', name: 'Marcus Garvey Square', emoji: '🏗️', kind: 'coop',
      neighborhood: 'Fillmore', address: '1680 Eddy St',
      lat: 37.7822, lng: -122.4330, coordsApprox: true,
      residents: 211, founded: 1972, status: 'active', inHSC: 'no',
      vibe: 'equity for the Fillmore',
      tags: ['justice', 'historical'],
      description: 'One of the first limited-equity housing cooperatives in the nation (1972): 211 units giving low-income Fillmore residents actual ownership stakes. Nearly foreclosed by 2008, then fully renovated 2009–2010 — a survival story for the co-op model.',
      links: [
        { label: 'renovation story', url: 'https://www.multihousingnews.com/sf-affordable-co-op-apartments-finish-major-renovation/' },
      ],
    },
    {
      id: 'amancio', name: 'Amancio Ergina Village', emoji: '🏘️', kind: 'coop',
      neighborhood: 'Western Addition', address: 'Ellis, Pierce, O\'Farrell & Scott Sts',
      lat: 37.7823, lng: -122.4369, coordsApprox: true,
      residents: 72, founded: 1986, status: 'active', inHSC: 'no',
      vibe: 'the union builds again',
      tags: ['justice'],
      description: 'The ILWU\'s second Western Addition housing act: 72 townhomes for low-to-moderate income families on two city acres, built 1986. Postmodern critic Charles Jencks singled it out as urban design done right.',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/index.php?title=The_ILWU_and_Western_Addition_Redevelopment_A-2' },
      ],
    },
    {
      id: 'columbusunited', name: 'Columbus United Cooperative', emoji: '🐉', kind: 'coop',
      neighborhood: 'Chinatown / North Beach', address: '53 Columbus Ave',
      lat: 37.7965, lng: -122.4042, coordsApprox: false,
      residents: 21, founded: 2009, status: 'active', inHSC: 'no',
      vibe: 'the eviction that never happened',
      tags: ['justice'],
      description: 'A former garment sweatshop turned 21-unit resident-owned co-op — the first community land trust project in the nation to use a housing cooperative explicitly to stop an eviction. Residents bought in at $10,000 a share after beating back demolition plans, with the Asian Law Caucus and Chinatown CDC at their side.',
      funFact: 'The first SF Community Land Trust building ever.',
      links: [
        { label: 'sfclt story', url: 'https://sfclt.org/home-for-good-five-decades-of-stability-at-columbus-united-cooperative/' },
      ],
    },
    {
      id: 'pigeonpalace', name: 'Pigeon Palace', emoji: '🐦', kind: 'coop',
      neighborhood: 'Mission', address: '2840-2848 Folsom St',
      lat: 37.7517, lng: -122.4143, coordsApprox: false,
      residents: 6, founded: 2015, status: 'active', inHSC: 'no',
      vibe: 'the Victorian that refused to flip',
      tags: ['justice', 'art'],
      description: 'A 1903 Queen Anne whose landlord Frances Carati spent 50 years renting cheap to artists and refusing to sell. When she went into care, her tenants — with SFCLT and the Small Sites Program — bought it off the speculative market in 2015 and run it as a co-op. New resident-painted mural as of 2025.',
      funFact: 'Named for the pigeons Frances fed daily; the co-op keeps the name in her honor.',
      links: [
        { label: 'pigeonpalace.org', url: 'https://www.pigeonpalace.org/' },
      ],
    },
    {
      id: 'northridge', name: 'Northridge Cooperative Homes', emoji: '🌉', kind: 'coop',
      neighborhood: 'Bayview-Hunters Point', lat: 37.7256, lng: -122.3750, coordsApprox: true,
      residents: 300, foundedEst: 1970, status: 'active', inHSC: 'no',
      vibe: 'Bayview\'s co-op anchor',
      tags: ['justice'],
      description: 'A 300-unit nonprofit housing cooperative in Bayview-Hunters Point with its own Neighborhood Network Center for resident services — one of the largest resident-governed affordable communities in the city, with bay views to match.',
      links: [
        { label: 'northridgecoop.net', url: 'https://www.northridgecoop.net/' },
      ],
    },
    {
      id: 'ammelpark', name: 'Ammel Park Cooperative', emoji: '🪺', kind: 'coop',
      neighborhood: 'Hayes Valley / Civic Center', address: '656 Grove St',
      lat: 37.7778, lng: -122.4258, coordsApprox: false,
      residents: 120, foundedEst: 1970, status: 'active', inHSC: 'no',
      vibe: 'family co-op by City Hall',
      tags: ['justice', 'family'],
      description: 'A 120-unit HUD-subsidized family housing cooperative blocks from City Hall — one- to four-bedroom homes, community room, play structures, and co-op governance for low-income families in the middle of the city.',
      links: [
        { label: 'listing', url: 'https://www.publichousing.com/details/ammel_park_coop' },
      ],
    },
    {
      id: 'midtownpark', name: 'Midtown Park Apartments', emoji: '⏳', kind: 'coop',
      neighborhood: 'Fillmore', address: '1415 Scott St',
      lat: 37.7830, lng: -122.4372, coordsApprox: false,
      residents: 139, founded: 1964, status: 'active', inHSC: 'no',
      vibe: 'the co-op promise deferred',
      tags: ['justice', 'historical'],
      description: 'Built in 1964 on urban-renewal land with a promise: pay off the 40-year mortgage and the residents own it as a limited-equity co-op. Tenants finished the payments in 2007 — and are still waiting. Rent strikes (2022) and a 2023 LAFCo study keep the ownership fight alive; the only city-owned residential property in SF.',
      funFact: 'The mortgage is paid. The deed never moved. The organizing never stopped.',
      links: [
        { label: '48hills coverage', url: 'https://48hills.org/2019/11/two-big-victories-for-tenants-at-midtown-apartments/' },
      ],
    },
    {
      id: 'turk285', name: '285 Turk Cooperative', emoji: '🔑', kind: 'coop',
      neighborhood: 'Tenderloin', address: '285 Turk St',
      lat: 37.7830, lng: -122.4140, coordsApprox: false,
      residents: 40, founded: 2022, status: 'active', inHSC: 'no',
      vibe: 'the Tenderloin buys itself back',
      tags: ['justice'],
      description: 'A 7-story Tenderloin building — 30 households, 95% BIPOC — that SFCLT bought in 2022 after a rent-control loophole left it exposed for decades. Now on a five-year path to resident-owned limited-equity cooperative status.',
      links: [
        { label: 'bay\'s future', url: 'https://baysfuture.org/san-francisco-community-land-trust-ensures-285-turk-st-remains-affordable/' },
      ],
    },
    {
      id: 'fourteenth320', name: '320-324 14th Street', emoji: '🚩', kind: 'coop',
      neighborhood: 'Mission', address: '320-324 14th St',
      lat: 37.7682, lng: -122.4147, coordsApprox: false,
      residents: 16, founded: 2024, status: 'active', inHSC: 'no',
      vibe: 'the rent strike that bought the building',
      tags: ['justice'],
      description: 'Sixteen mostly Latino/a/x/e households went on rent strike in 2022 over deteriorating conditions — and ended up owning the outcome: SFCLT purchased the building in 2024 with a $4.25M regional grant, and the residents are forming a limited-equity co-op.',
      links: [
        { label: 'bahfa story', url: 'https://mtc.ca.gov/news/bahfa-helps-community-land-trusts-preserve-affordable-homes' },
      ],
    },
    {
      id: 'goodman', name: 'The Goodman Building', emoji: '🖼️', kind: 'coop',
      neighborhood: 'Van Ness / Polk Gulch', address: '1117 Geary Blvd',
      lat: 37.7855, lng: -122.4235, coordsApprox: false,
      residents: 30, founded: 1970, closedYear: 1983, status: 'closed', inHSC: 'no',
      vibe: 'the artists\' ten-year last stand',
      tags: ['historical', 'art', 'justice'],
      description: 'An 1860s building turned residential hotel where 25-30 artists — poster legend Wes Wilson among them, with Theatre Rhinoceros and the Lorraine Hansberry Theatre downstairs — fought the Redevelopment Agency\'s wrecking ball for a decade. They won landmark status in 1975, lost the eviction in 1983, and their ARTSDECO successor built "Goodman2" in Potrero Hill.',
      funFact: 'The preservation fight helped shape SF\'s landmark and artist-housing policy for decades after.',
      links: [
        { label: 'foundsf', url: 'https://www.foundsf.org/index.php?title=The_Goodman_Building' },
        { label: 'sf heritage', url: 'https://sfheritage.org/news/heritage-50-the-goodman-building/' },
      ],
    },

    /* ================= cohousing: the East Bay village model ================= */
    {
      id: 'swansmarket', name: 'Swan\'s Market Cohousing', emoji: '🦢', kind: 'cohousing',
      neighborhood: 'Old Oakland', lat: 37.8072, lng: -122.2715, coordsApprox: true,
      residents: 40, founded: 2000, status: 'active', inHSC: 'no',
      vibe: 'a village inside a landmark',
      tags: ['family'],
      description: 'Twenty cohousing units retrofitted into Oakland\'s beloved 1917 Swan\'s Market building, two blocks from BART — shared dining, a common house, and a food hall for a front yard.',
      funFact: 'North America\'s 50th cohousing community, and one of the first built inside a historic landmark.',
      links: [
        { label: 'cohousing directory', url: 'https://cohousingalliance.org/communities/swan%E2%80%99s-market-cohousing/' },
      ],
    },
    {
      id: 'phoenixcommons', name: 'Phoenix Commons', emoji: '🐦‍🔥', kind: 'cohousing',
      neighborhood: 'Jingletown (Oakland)', lat: 37.8125, lng: -122.2495, coordsApprox: true,
      residents: 41, founded: 2016, status: 'active', inHSC: 'no',
      vibe: 'aging on purpose, together',
      tags: ['wellness', 'family'],
      description: 'A 41-unit senior (55+) cohousing community on the Oakland estuary: twice-weekly shared dinners, hobby rooms, a community garden, and consensus committees — a deliberate answer to aging alone.',
      links: [
        { label: 'phoenixcommons.com', url: 'https://phoenixcommons.com/' },
      ],
    },
    {
      id: 'temescalcommons', name: 'Temescal Commons', emoji: '🍑', kind: 'cohousing',
      neighborhood: 'Temescal (Oakland)', lat: 37.8295, lng: -122.2663, coordsApprox: true,
      residents: 20, founded: 2000, status: 'active', inHSC: 'no',
      vibe: 'a block that became a village',
      tags: ['family'],
      description: 'Eleven units retrofitted from three adjacent 1920s duplexes in Temescal — weekly meals, work parties, and multigenerational neighboring, eight minutes\' walk from MacArthur BART.',
      funFact: 'Five families pioneered the "retrofit" model here: turn the block you already live on into cohousing.',
      links: [
        { label: 'temescalcommons.org', url: 'https://www.temescalcommons.org/' },
      ],
    },
    {
      id: 'doylestreet', name: 'Doyle Street Cohousing', emoji: '🧱', kind: 'cohousing',
      neighborhood: 'Emeryville', lat: 37.8312, lng: -122.2840, coordsApprox: true,
      residents: 20, founded: 1992, status: 'active', inHSC: 'no',
      vibe: 'where US cohousing began',
      tags: ['family', 'historical'],
      description: 'Twelve units in a retrofitted brick industrial building — common house, workshop, hot tub, big organic garden — designed by Katie McCamant and Chuck Durrett, the architects who imported cohousing from Denmark.',
      funFact: 'America\'s second-ever cohousing community (1992).',
      links: [
        { label: 'emeryville-cohousing.org', url: 'http://www.emeryville-cohousing.org/' },
      ],
    },
    {
      id: 'berkeleycohousing', name: 'Berkeley Cohousing', emoji: '🌄', kind: 'cohousing',
      neighborhood: 'Berkeley', lat: 37.867, lng: -122.279, coordsApprox: true,
      residents: 30, founded: 1994, status: 'active', inHSC: 'no',
      vibe: 'the California template',
      tags: ['family'],
      description: 'One of California\'s first cohousing communities (1994), blending renovated existing homes with new construction around a common house — the template much of the state\'s cohousing movement copied.',
      links: [
        { label: 'cohousing california', url: 'https://www.calcoho.org/communities' },
      ],
    },
  ],
};
