-- ============================================
-- Persisted music-type classification
-- Migration 101
-- The 8-bucket taxonomy (electronic/rock/pop/hiphop/jazz/folk/world/other)
-- was derived client-side from genre keywords; persisting makes it queryable,
-- consistent across clients, and available to recs/metrics.
-- classify_music_type() mirrors the client keyword matcher; enrich-event's
-- AI refines per event; run_events_maintenance() self-heals NULL/other rows.
-- Backfill at apply time classified 993 rows.
-- ============================================
-- (full SQL as applied via MCP — see remote migration 101_music_type_column)
