/**
 * Storage Module
 * Handles persistence with localStorage (JSON-based)
 */

const STORAGE_KEY = 'things-i-like-data';

// Default data structure
const DEFAULT_DATA = {
  links: [],
  categories: {
    uncategorized: {
      created: new Date().toISOString(),
      pinned: true,
      autoGenerated: false,
      itemCount: 0
    }
  },
  meta: {
    version: 1,
    lastModified: new Date().toISOString()
  }
};

/**
 * Load all data from storage
 * @returns {Object} - Complete data object
 */
export function loadData() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const data = JSON.parse(stored);
      // Ensure required structure exists
      return {
        ...DEFAULT_DATA,
        ...data,
        categories: {
          ...DEFAULT_DATA.categories,
          ...(data.categories || {})
        }
      };
    }
  } catch (error) {
    console.error('Failed to load data:', error);
  }
  return { ...DEFAULT_DATA };
}

/**
 * Save all data to storage
 * @param {Object} data - Complete data object
 */
export function saveData(data) {
  try {
    data.meta.lastModified = new Date().toISOString();
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (error) {
    console.error('Failed to save data:', error);
    throw new Error('Failed to save data');
  }
}

/**
 * Get all links
 * @returns {Array} - Array of link objects
 */
export function getAllLinks() {
  const data = loadData();
  return data.links || [];
}

/**
 * Get links by category
 * @param {string} category - Category name
 * @returns {Array} - Array of link objects
 */
export function getLinksByCategory(category) {
  const links = getAllLinks();
  if (category === 'all') return links;
  return links.filter(link => link.category === category);
}

/**
 * Get a single link by ID
 * @param {string} id - Link ID
 * @returns {Object|null} - Link object or null
 */
export function getLinkById(id) {
  const links = getAllLinks();
  return links.find(link => link.id === id) || null;
}

/**
 * Check if a URL already exists
 * @param {string} url - URL to check
 * @returns {Object|null} - Existing link or null
 */
export function findLinkByUrl(url) {
  const links = getAllLinks();
  const normalizedUrl = url.toLowerCase().replace(/\/+$/, '');
  return links.find(link =>
    link.url.toLowerCase().replace(/\/+$/, '') === normalizedUrl
  ) || null;
}

/**
 * Add a new link
 * @param {Object} link - Link object to add
 * @returns {Object} - Added link
 */
export function addLink(link) {
  const data = loadData();

  // Check for duplicate
  const existing = findLinkByUrl(link.url);
  if (existing) {
    throw new Error(`This link already exists in "${existing.category}"`);
  }

  // Add timestamp and defaults
  const newLink = {
    ...link,
    addedAt: new Date().toISOString(),
    userVerified: false
  };

  data.links.push(newLink);

  // Update category item count
  const category = link.category || 'uncategorized';
  if (data.categories[category]) {
    data.categories[category].itemCount = (data.categories[category].itemCount || 0) + 1;
  }

  saveData(data);
  return newLink;
}

/**
 * Update a link
 * @param {string} id - Link ID
 * @param {Object} updates - Fields to update
 * @returns {Object} - Updated link
 */
export function updateLink(id, updates) {
  const data = loadData();
  const index = data.links.findIndex(link => link.id === id);

  if (index === -1) {
    throw new Error('Link not found');
  }

  const oldCategory = data.links[index].category;
  const newCategory = updates.category;

  // Update the link
  data.links[index] = {
    ...data.links[index],
    ...updates,
    modifiedAt: new Date().toISOString()
  };

  // Update category counts if category changed
  if (newCategory && newCategory !== oldCategory) {
    if (data.categories[oldCategory]) {
      data.categories[oldCategory].itemCount = Math.max(0, (data.categories[oldCategory].itemCount || 1) - 1);
    }
    if (data.categories[newCategory]) {
      data.categories[newCategory].itemCount = (data.categories[newCategory].itemCount || 0) + 1;
    }
  }

  saveData(data);
  return data.links[index];
}

/**
 * Delete a link
 * @param {string} id - Link ID
 */
export function deleteLink(id) {
  const data = loadData();
  const link = data.links.find(l => l.id === id);

  if (!link) {
    throw new Error('Link not found');
  }

  // Update category count
  if (data.categories[link.category]) {
    data.categories[link.category].itemCount = Math.max(0, (data.categories[link.category].itemCount || 1) - 1);
  }

  data.links = data.links.filter(l => l.id !== id);
  saveData(data);
}

/**
 * Get all categories
 * @returns {Object} - Categories object
 */
export function getCategories() {
  const data = loadData();
  return data.categories || {};
}

/**
 * Get category with its items
 * @param {string} name - Category name
 * @returns {Object} - Category with items
 */
export function getCategoryWithItems(name) {
  const data = loadData();
  const category = data.categories[name];

  if (!category) return null;

  return {
    ...category,
    name,
    items: data.links.filter(link => link.category === name)
  };
}

/**
 * Create a new category
 * @param {string} name - Category name
 * @param {Object} options - Category options
 * @returns {Object} - Created category
 */
export function createCategory(name) {
  const data = loadData();
  const normalizedName = name.toLowerCase().replace(/\s+/g, '-');

  if (data.categories[normalizedName]) {
    throw new Error('Category already exists');
  }

  data.categories[normalizedName] = {
    created: new Date().toISOString(),
    pinned: false,
    autoGenerated: true,
    itemCount: 0
  };

  saveData(data);
  return { name: normalizedName, ...data.categories[normalizedName] };
}

/**
 * Rename a category
 * @param {string} oldName - Current name
 * @param {string} newName - New name
 */
export function renameCategory(oldName, newName) {
  const data = loadData();
  const normalizedOld = oldName.toLowerCase();
  const normalizedNew = newName.toLowerCase().replace(/\s+/g, '-');

  if (!data.categories[normalizedOld]) {
    throw new Error('Category not found');
  }

  if (data.categories[normalizedNew]) {
    throw new Error('A category with this name already exists');
  }

  // Move category data
  data.categories[normalizedNew] = data.categories[normalizedOld];
  delete data.categories[normalizedOld];

  // Update links
  data.links = data.links.map(link => {
    if (link.category === normalizedOld) {
      return { ...link, category: normalizedNew };
    }
    return link;
  });

  saveData(data);
}

/**
 * Delete a category (moves items to uncategorized)
 * @param {string} name - Category name
 */
export function deleteCategory(name) {
  const data = loadData();
  const normalizedName = name.toLowerCase();

  if (normalizedName === 'uncategorized') {
    throw new Error('Cannot delete uncategorized');
  }

  if (!data.categories[normalizedName]) {
    throw new Error('Category not found');
  }

  // Move links to uncategorized
  let movedCount = 0;
  data.links = data.links.map(link => {
    if (link.category === normalizedName) {
      movedCount++;
      return { ...link, category: 'uncategorized' };
    }
    return link;
  });

  // Update uncategorized count
  data.categories.uncategorized.itemCount = (data.categories.uncategorized.itemCount || 0) + movedCount;

  // Remove category
  delete data.categories[normalizedName];

  saveData(data);
}

/**
 * Merge two categories
 * @param {string} sourceCategory - Category to merge from
 * @param {string} targetCategory - Category to merge into
 */
export function mergeCategories(sourceCategory, targetCategory) {
  const data = loadData();

  if (!data.categories[sourceCategory] || !data.categories[targetCategory]) {
    throw new Error('Category not found');
  }

  // Move links from source to target
  let movedCount = 0;
  data.links = data.links.map(link => {
    if (link.category === sourceCategory) {
      movedCount++;
      return { ...link, category: targetCategory };
    }
    return link;
  });

  // Update target count
  data.categories[targetCategory].itemCount = (data.categories[targetCategory].itemCount || 0) + movedCount;

  // Remove source category
  delete data.categories[sourceCategory];

  saveData(data);
}

/**
 * Get uncategorized items for cluster detection
 * @returns {Array} - Uncategorized link items
 */
export function getUncategorizedItems() {
  return getLinksByCategory('uncategorized');
}

/**
 * Move multiple links to a category
 * @param {string[]} ids - Array of link IDs
 * @param {string} category - Target category
 */
export function bulkMoveToCategory(ids, category) {
  const data = loadData();

  for (const id of ids) {
    const index = data.links.findIndex(link => link.id === id);
    if (index !== -1) {
      const oldCategory = data.links[index].category;

      // Update counts
      if (data.categories[oldCategory]) {
        data.categories[oldCategory].itemCount = Math.max(0, (data.categories[oldCategory].itemCount || 1) - 1);
      }
      if (data.categories[category]) {
        data.categories[category].itemCount = (data.categories[category].itemCount || 0) + 1;
      }

      data.links[index].category = category;
    }
  }

  saveData(data);
}

/**
 * Export data as JSON
 * @returns {string} - JSON string
 */
export function exportData() {
  const data = loadData();
  return JSON.stringify(data, null, 2);
}

/**
 * Import data from JSON
 * @param {string} json - JSON string
 */
export function importData(json) {
  try {
    const data = JSON.parse(json);
    if (!data.links || !data.categories) {
      throw new Error('Invalid data format');
    }
    saveData(data);
  } catch (error) {
    throw new Error('Failed to import data: ' + error.message);
  }
}

/**
 * Clear all data
 */
export function clearAllData() {
  localStorage.removeItem(STORAGE_KEY);
}
